(async()=>{
const assert=(v,m)=>{if(!v)throw Error(m);},sleep=ms=>new Promise(r=>setTimeout(r,ms));let passed=0,failed=0;async function test(name,fn){const li=document.createElement('li');try{await fn();li.textContent=`PASS ${name}`;passed++;}catch(e){li.textContent=`FAIL ${name}: ${e.message}`;failed++;}document.getElementById('results').append(li);}
const fixture=document.getElementById('fixture'),layout=[9,2,7,4,1,6,3,8,5];let view,settled,phase;
function mount(){settled=null;phase='COUNTDOWN';const p=MiniGames.registry.get('number_memory'),op={...p.create(),status:phase,bet:{stake:'100'}};op.payload.layout=layout;op.config={...op.config,countdownMs:10,revealMs:120,recallLimitMs:2000};view=MemoryView.mount({container:fixture,opportunity:op,command:async type=>{phase=type==='running'?'MEMORIZE':'RECALL';view.update({...op,status:phase});},settle:r=>settled=r});return op;}
async function until(fn){const end=performance.now()+3000;while(!fn()){if(performance.now()>end)throw Error('전환 시간 초과');await sleep(5);}}
const click=n=>fixture.querySelector(`[data-cell="${layout.indexOf(n)}"]`).click();
await test('공개와 동시 가림 · 숨은 숫자와 접근성 이름 제거',async()=>{mount();assert([...fixture.querySelectorAll('[data-cell]')].every(b=>b.textContent==='·'),'준비 숫자 노출');await until(()=>phase==='MEMORIZE'&&fixture.querySelector('.remember'));assert([...fixture.querySelectorAll('[data-cell]')].map(b=>b.textContent).join(',')===layout.join(','),'공개 오류');click(1);assert(fixture.querySelector('#memory-count').textContent==='0 / 9 정답','공개 중 입력');await until(()=>phase==='RECALL');assert([...fixture.querySelectorAll('[data-cell]')].every(b=>b.textContent==='·'&&b.getAttribute('aria-label').includes('가려진 칸')),'숨은 정답 노출');view.dispose();});
await test('빠른 연속 정답 · 재터치 무시 · 오답 즉시 종료',async()=>{mount();await until(()=>phase==='RECALL');for(let n=1;n<=5;n++)click(n);click(1);assert(fixture.querySelector('#memory-count').textContent==='5 / 9 정답','중복/빠른 입력');click(7);assert(settled.reason==='wrong'&&settled.correctCount===5,'오답 판정');assert(settled.actualRevealMs>=120,'공개 기록');view.dispose();});
await test('9개 완료와 360px 화면 기준 칸 크기',async()=>{mount();await until(()=>phase==='RECALL');const bounds=fixture.querySelector('[data-cell]').getBoundingClientRect();assert(bounds.width>=64&&bounds.height>=64,'터치 영역');assert(fixture.scrollWidth<=282,'보드 넘침');for(let n=1;n<=9;n++)click(n);assert(settled.reason==='complete'&&settled.correctCount===9,'전체 정답');view.dispose();});
await test('공개 중 누른 손가락 · 동시 터치 · 드래그 · 중복 클릭 무시',async()=>{mount();const board=fixture.querySelector('.memory-board');board.setPointerCapture=()=>{};const cell=n=>fixture.querySelector(`[data-cell="${layout.indexOf(n)}"]`),pointer=(target,type,id)=>target.dispatchEvent(new PointerEvent(type,{bubbles:true,pointerId:id,button:0}));await until(()=>phase==='MEMORIZE');pointer(cell(1),'pointerdown',1);await until(()=>phase==='RECALL');pointer(cell(1),'pointermove',1);pointer(cell(2),'pointerdown',2);assert(fixture.querySelector('#memory-count').textContent==='0 / 9 정답','누른 채 입력');pointer(board,'pointerup',1);pointer(cell(1),'pointerdown',3);pointer(cell(2),'pointerdown',4);cell(2).dispatchEvent(new MouseEvent('click',{bubbles:true,detail:1}));pointer(cell(2),'pointermove',3);assert(fixture.querySelector('#memory-count').textContent==='1 / 9 정답','다중 입력');pointer(board,'pointerup',3);pointer(cell(2),'pointerdown',5);assert(fixture.querySelector('#memory-count').textContent==='2 / 9 정답','새 터치 실패');view.dispose();});
await test('답변 시간 초과는 부분 정답으로 자동 종료',async()=>{mount();await until(()=>phase==='RECALL');for(let n=1;n<=7;n++)click(n);await until(()=>settled);assert(settled.reason==='timeout'&&settled.correctCount===7,'시간 초과 기록');assert(MemoryEngine.judge({payload:{layout},config:MemoryEngine.CONFIG},settled).multiplier===2,'부분 배당');view.dispose();});
const store=new ProgressStore(`memory-test-${MiniGames.uid()}`,TILE_CASES);await store.open();
async function offer(){await store.update(g=>{g.data=TileState.fresh();g.data.status='minigame';g.data.cumulativeScore='1076';g.data.pendingMiniGame={...MiniGames.registry.get('number_memory').create(),type:'number_memory',miniGameId:'memory',status:'OFFERED',payload:{layout}};});}
await test('동시 베팅과 동시 정산은 한 번씩만 반영',async()=>{await offer();const starts=await Promise.allSettled([store.update(g=>g.mini('start',{stake:'500',expectedBalance:'1076'},'a')),store.update(g=>g.mini('start',{stake:'500',expectedBalance:'1076'},'b'))]);assert(starts.filter(r=>r.status==='fulfilled').length===1,'중복 베팅');await store.update(g=>{g.mini('running');g.mini('recall');});const s=new MemoryEngine.Session(layout);s.reveal(0);s.hide(MemoryEngine.CONFIG.revealMs);for(let n=1;n<=9;n++)s.input(layout.indexOf(n),s.recallStart+100+n);await Promise.all([store.update(g=>g.mini('settle',s.result,'pay')),store.update(g=>g.mini('settle',s.result,'pay2'))]);const {model}=await store.update(()=>{});assert(model.data.cumulativeScore==='3076'&&model.data.miniGameHistory.length===1,'중복 지급');});
await test('시작 저장 실패 롤백 · 공개/답변 중단 복구',async()=>{await offer();try{await store.update(g=>{g.mini('start',{stake:'500',expectedBalance:'1076'});g.data.bad=()=>{};});}catch{}const restored=await store.update(()=>{});assert(restored.model.data.cumulativeScore==='1076','부분 차감');for(const recall of [false,true]){await offer();await store.update(g=>{g.mini('start',{stake:'500',expectedBalance:'1076'});g.mini('running');if(recall)g.mini('recall');});const {model}=await store.initialize();assert(model.data.cumulativeScore==='576'&&model.data.pendingMiniGame.result.multiplier===0,'중단 복구');}});
store.db.close();indexedDB.deleteDatabase(store.name);fixture.innerHTML='';document.getElementById('summary').textContent=`${passed} passed · ${failed} failed`;
})();
