const assert=require('node:assert/strict'),M=require('./engine.js'),registry=require('../number-tiles/minigames/catalog.js'),{Game,fresh}=require('../number-tiles/state.js');require('../number-tiles/cases.js');let count=0;
const test=(n,f)=>{f();console.log('PASS',n);count++;},layout=[9,2,7,4,1,6,3,8,5];
function session(){const s=new M.Session(layout);s.reveal(100);s.hide(100+M.CONFIG.revealMs);return s;}
function hit(s,n,t=100){return s.input(layout.indexOf(n),s.recallStart+t);}
function model(){const d=fresh(),p=registry.get('number_memory');d.status='minigame';d.cumulativeScore='1076';d.pendingMiniGame={...p.create(),miniGameId:'memory-test',sourceRoundId:'round',type:p.type,status:'OFFERED'};d.pendingMiniGame.payload.layout=layout;return new Game(globalThis.TILE_CASES,d,{recover:false});}
test('valid permutations and invalid layouts',()=>{for(let i=0;i<500;i++)assert(M.validLayout(M.layout()));for(const a of [[],[1,2,3,4,5,6,7,8,8],[0,2,3,4,5,6,7,8,9]])assert(!M.validLayout(a));let values=[4294967295,0,0,0,0,0,0,0,0];assert(M.validLayout(M.layout(()=>values.shift())));});
test('countdown, exact reveal boundary, actual delayed hide time',()=>{const s=new M.Session(layout);s.input(4,0);assert.equal(s.correctCount,0);s.reveal(100);assert(!s.hide(4099.9));s.input(4,4100);assert.equal(s.correctCount,0);assert(s.hide(4200));s.input(4,4199);assert.equal(s.correctCount,0);s.input(4,4200);assert.equal(s.correctCount,1);assert.equal(s.interrupt().actualRevealMs,4100);});
test('sequential answers, repeated cells, outside input and first wrong',()=>{const s=session();for(let n=1;n<=3;n++)hit(s,n);assert.equal(s.correctCount,3);hit(s,1);s.input(-1,2300);assert.equal(s.correctCount,3);hit(s,5);assert.equal(s.result.reason,'wrong');assert.equal(s.correctCount,3);hit(s,4);assert.equal(s.correctCount,3);});
test('all reward tiers and partial timeout',()=>{for(let k=0;k<=9;k++){const s=session();for(let n=1;n<=k;n++)hit(s,n);if(k<9)s.timeout(s.recallStart+15000);const r=M.judge({payload:{layout},config:M.CONFIG},s.result);assert.equal(r.correctCount,k);assert.equal(r.multiplier,k===9?5:k>=7?2:k>=5?1:0);}for(const k of [5,7]){const s=session();for(let n=1;n<=k;n++)hit(s,n);hit(s,k+2);assert.equal(M.judge({payload:{layout},config:M.CONFIG},s.result).multiplier,k===5?1:2);}});
test('15.000 final answer valid, later input expires, delayed processing timestamp valid',()=>{for(const t of [15000,15000.001]){const s=session();for(let n=1;n<=8;n++)hit(s,n);hit(s,9,t);assert.equal(s.result.reason,t===15000?'complete':'timeout');assert.equal(s.correctCount,t===15000?9:8);}const s=session();hit(s,1,15000);assert.equal(s.result.reason,'timeout');assert.equal(s.result.correctCount,1);assert.equal(M.normalizeTimestamp(100002300,2400,100000000),2400);assert.equal(M.normalizeTimestamp(1700000002300,2400,1700000000000),2300);});
test('judge rejects fabricated results and unordered records',()=>{const op={payload:{layout},config:M.CONFIG};assert.throws(()=>M.judge(op,{reason:'complete',inputs:[]}));assert.throws(()=>M.judge(op,{reason:'timeout',inputs:[{cell:4,at:10},{cell:1,at:9}]}));assert.throws(()=>M.judge(op,{reason:'timeout',inputs:[{cell:4,at:15001}]}));});
test('all started states recover as zero once; offered layout survives',()=>{for(const phase of ['COUNTDOWN','MEMORIZE','RECALL']){const g=model();g.mini('start',{stake:'500',expectedBalance:'1076'});if(phase!=='COUNTDOWN')g.mini('running');if(phase==='RECALL')g.mini('recall');assert.equal(g.data.pendingMiniGame.status,phase);const recovered=new Game(globalThis.TILE_CASES,g.data);assert.equal(recovered.data.cumulativeScore,'576');assert.equal(recovered.data.pendingMiniGame.result.endReason,'interrupted');assert.equal(new Game(globalThis.TILE_CASES,recovered.data).data.miniGameHistory.length,1);}const g=model();assert.deepEqual(new Game(globalThis.TILE_CASES,g.data).data.pendingMiniGame.payload.layout,layout);});
test('wallet 5x / 1x / 0x and duplicate settlement',()=>{for(const k of [9,5,0]){const g=model();g.mini('start',{stake:'500',expectedBalance:'1076'},'bet');g.mini('start',{stake:'500',expectedBalance:'1076'},'bet');g.mini('running');assert.throws(()=>g.mini('settle',{reason:'timeout'}));g.mini('recall');const s=session();for(let n=1;n<=k;n++)hit(s,n);if(k<9)s.timeout(s.recallStart+M.CONFIG.recallLimitMs);g.mini('settle',s.result,'pay');g.mini('settle',s.result,'pay-again');assert.equal(g.data.cumulativeScore,k===9?'3076':k===5?'1076':'576');assert.equal(g.data.miniGameHistory.length,1);}});
test('interruption after seven hits pays zero; low balance and invalid case blocked',()=>{const s=session();for(let n=1;n<=7;n++)hit(s,n);assert.equal(M.judge({payload:{layout},config:M.CONFIG},s.interrupt()).multiplier,0);const g=model();g.data.cumulativeScore='99';assert.throws(()=>g.mini('start',{stake:'100',expectedBalance:'99'}));assert.equal(g.data.cumulativeScore,'99');g.data.cumulativeScore='1076';g.data.pendingMiniGame.payload.layout=[1];assert.throws(()=>g.mini('start',{stake:'100',expectedBalance:'1076'}));});
test('equal five-way draw and final stage paths',()=>{assert.equal(registry.draw(()=>0).type,'number_memory');assert.equal(registry.draw(()=>.3).type,'dice_roll');assert.equal(registry.draw(()=>.5).type,'timer_stop');assert.deepEqual(registry.list().map(p=>p.weight),[1,1,1,1,1]);for(const skip of [true,false]){const g=model();g.data.currentTarget=21;if(skip)g.mini('skip');else{g.mini('start',{stake:'100',expectedBalance:'1076'});g.mini('settle',{reason:'interrupted'});}g.next();assert.equal(g.data.status,'finished');}});
console.log(`${count} memory suites passed`);
