(function(root){
  'use strict';
  const E=root.MemoryEngine;
  root.MemoryView={mount(ctx){
    const op=ctx.opportunity,c=op.config,session=new E.Session(op.payload.layout,c),el=ctx.container;
    let disposed=false,locked=false,frame=0,countTimer=0,drainTimer=0,activePointer=null,lastFrame=0,longFrameCount=0,maxFrameMs=0;
    const countEnd=performance.now()+c.countdownMs;
    el.innerHTML=`<div class="memory-topline"><span class="eyebrow">A MOMENT TO REMEMBER</span><span>베팅 ${BigInt(op.bet.stake).toLocaleString()}점</span></div><h2>순간 기억</h2><div class="memory-prompt"><span id="memory-phase">잠시 후 공개돼요</span><strong id="memory-prompt">3</strong><p id="memory-caption">숫자 위치를 기억하고, 1부터 차례대로.</p></div><div class="memory-meter"><i id="memory-meter"></i></div><div class="memory-meta"><span id="memory-clock">준비 중</span><span id="memory-count">0 / 9 정답</span></div><div class="memory-board" aria-label="숫자 기억 보드">${Array.from({length:9},(_,i)=>`<button type="button" data-cell="${i}" aria-label="${Math.floor(i/3)+1}행 ${i%3+1}열, 가려진 칸"><span>·</span></button>`).join('')}</div><div class="memory-ladder"><span data-tier="5">5개 <b>×1</b></span><span data-tier="7">7개 <b>×2</b></span><span data-tier="9">9개 <b>×5</b></span></div><p class="memory-footnote">첫 오답에서 종료 · 맞춘 칸은 다시 눌러도 괜찮아요</p>`;
    const q=s=>el.querySelector(s),board=q('.memory-board'),cells=[...board.querySelectorAll('button')];
    function paint(){const reveal=session.phase==='MEMORIZE';cells.forEach((button,i)=>{const correct=session.revealed.includes(i),shown=reveal||correct;button.innerHTML=shown?`<span>${session.layout[i]}</span>${correct?'<small>✓</small>':''}`:'<span>·</span>';button.classList.toggle('remember',reveal);button.classList.toggle('correct',correct);button.setAttribute('aria-label',shown?`${session.layout[i]}${correct?', 정답':''}`:`${Math.floor(i/3)+1}행 ${i%3+1}열, 가려진 칸`);button.setAttribute('aria-disabled',String(session.phase!=='RECALL'||correct));});q('#memory-count').textContent=`${session.correctCount} / 9 정답`;el.querySelectorAll('[data-tier]').forEach(n=>n.classList.toggle('earned',session.correctCount>=Number(n.dataset.tier)));}
    function payload(result){return {...result,longFrameCount,maxFrameMs};}
    function finish(result){if(locked||disposed)return;locked=true;cancelAnimationFrame(frame);clearTimeout(countTimer);clearTimeout(drainTimer);q('#memory-prompt').textContent='기록 완료';q('#memory-caption').textContent='결과를 저장하고 있어요.';cells.forEach(b=>b.setAttribute('aria-disabled','true'));ctx.settle(payload(result));}
    function hide(now){if(!session.hide(now))return;paint();q('#memory-phase').textContent='RECALL · 순서대로 찾아보세요';q('#memory-prompt').textContent='숫자 1 찾기';q('#memory-caption').textContent='기억한 위치를 톡, 톡.';ctx.command('recall').catch(()=>finish(session.interrupt()));}
    function advance(now){if(disposed||locked)return;if(session.phase==='MEMORIZE'&&now>=session.memorizeStart+c.revealMs)hide(now);if(session.phase==='MEMORIZE'){const left=Math.max(0,c.revealMs-(now-session.memorizeStart));q('#memory-clock').textContent=`공개 ${(left/1000).toFixed(1)}초`;q('#memory-meter').style.width=`${left/c.revealMs*100}%`;}else if(session.phase==='RECALL'){const left=Math.max(0,c.recallLimitMs-(now-session.recallStart));q('#memory-clock').textContent=`남은 시간 ${(left/1000).toFixed(1)}초`;q('#memory-meter').style.width=`${left/c.recallLimitMs*100}%`;if(left===0&&!drainTimer){q('#memory-caption').textContent='마감 전 입력을 확인하고 있어요.';drainTimer=setTimeout(()=>{if(!disposed&&!locked)finish(session.timeout(performance.now()));},c.inputDrainMs);}}}
    function tick(now){if(disposed||locked)return;if(lastFrame){const gap=now-lastFrame;maxFrameMs=Math.max(maxFrameMs,gap);if(gap>50)longFrameCount++;}lastFrame=now;advance(now);frame=requestAnimationFrame(tick);}
    function memorize(){if(disposed||locked||session.phase!=='COUNTDOWN')return;frame=requestAnimationFrame(now=>{if(disposed||locked)return;session.reveal(now);paint();q('#memory-phase').textContent='MEMORIZE · 지금, 기억하세요';q('#memory-prompt').textContent='위치를 기억하세요';q('#memory-caption').textContent=`${c.revealMs/1000}초 뒤 숫자가 모두 가려져요.`;tick(now);});}
    function choose(cell,e){if(disposed||locked)return;const now=performance.now(),stamp=E.normalizeTimestamp(e.timeStamp,now,performance.timeOrigin);advance(now);const r=session.input(cell,stamp);if(r){finish(r);return;}if(session.phase==='RECALL'){paint();q('#memory-prompt').textContent=`숫자 ${session.correctCount+1} 찾기`;}}
    board.onpointerdown=e=>{if(activePointer!==null||e.button!==0||disposed||locked)return;activePointer=e.pointerId;board.setPointerCapture(e.pointerId);e.preventDefault();const b=e.target.closest('[data-cell]');if(b)choose(Number(b.dataset.cell),e);};
    board.onpointerup=board.onpointercancel=board.onlostpointercapture=e=>{if(e.pointerId===activePointer)activePointer=null;};
    board.onclick=e=>{if(e.detail===0&&activePointer===null){const b=e.target.closest('[data-cell]');if(b)choose(Number(b.dataset.cell),e);}};
    board.onkeydown=e=>{if(e.repeat&&(e.key==='Enter'||e.key===' '))e.preventDefault();};
    function countdown(){if(disposed||locked)return;const left=countEnd-performance.now();if(left<=0){ctx.command('running').catch(()=>finish(session.interrupt()));return;}q('#memory-prompt').textContent=Math.ceil(left/1000);countTimer=setTimeout(countdown,Math.min(left,100));}
    function update(next){if(next.status==='MEMORIZE')memorize();}paint();if(op.status==='COUNTDOWN')countdown();else memorize();
    return {update,interruption:()=>payload(session.interrupt()),dispose(){disposed=true;cancelAnimationFrame(frame);clearTimeout(countTimer);clearTimeout(drainTimer);}};
  }};
})(globalThis);
