(async()=>{
  const E=ReverseEngine,assert=(v,m)=>{if(!v)throw Error(m);},sleep=ms=>new Promise(r=>setTimeout(r,ms));let passed=0,failed=0;
  async function test(name,fn){const li=document.createElement('li');try{await fn();li.textContent=`PASS ${name}`;passed++;}catch(e){li.textContent=`FAIL ${name}: ${e.message}`;failed++;}finally{view?.dispose();}document.getElementById('results').append(li);}
  async function until(fn){const end=performance.now()+3500;while(!fn()){if(performance.now()>end)throw Error('전환 시간 초과');await sleep(5);}}
  const fixture=document.getElementById('fixture'),questions=Array.from({length:10},(_,i)=>({questionId:`q${i+1}`,mode:i%2?'OPPOSITE':'SAME',direction:'UP',expectedDirection:i%2?'DOWN':'UP'}));let view,settled,phase,op;
  function mount(overrides={}){settled=null;phase='COUNTDOWN';op={...MiniGames.registry.get('reverse_tap').create(),status:phase,bet:{stake:'100'},payload:{questions}};op.config={...op.config,countdownMs:10,feedbackMs:40,...overrides};view=ReverseView.mount({container:fixture,opportunity:op,command:async type=>{phase={running:'QUESTION',feedback:'FEEDBACK',question:'QUESTION'}[type];view.update({...op,status:phase});},settle:r=>settled=r});}
  const button=d=>fixture.querySelector(`[data-dir="${d}"]`),click=d=>button(d).click(),question=n=>fixture.querySelector('#reverse-question')?.textContent===`문제 ${n} / 10`;
  await test('준비 문제 숨김 · 10개 연속 성공 · 피드백 동안 이전 문제 유지',async()=>{mount();assert(fixture.querySelector('#reverse-rule').textContent==='준비하세요','문제 노출');click('UP');for(let i=0;i<10;i++){await until(()=>question(i+1));assert(fixture.querySelector('#reverse-rule').textContent===(i%2?'반대로':'그대로'),'규칙 표시');assert(fixture.querySelector('#reverse-arrow').textContent==='↑','화살표 표시');click(questions[i].expectedDirection);if(i<9){assert(phase==='FEEDBACK','피드백 상태');click(questions[i+1].expectedDirection);assert(question(i+1),'다음 문제 조기 공개');}}assert(settled?.reason==='complete'&&settled.correctCount===10,'연속 성공');assert(E.judge(op,settled).multiplier===5,'배당');});
  await test('오답 후 재입력 무시 · 시간 초과 미응답 정산',async()=>{mount();await until(()=>question(1));click('DOWN');click('UP');assert(settled.reason==='wrong'&&settled.correctCount===0&&settled.records.length===1,'오답 잠금');view.dispose();mount({answerLimitMs:60,inputDrainMs:10});await until(()=>settled);assert(settled.reason==='timeout'&&settled.records[0].selectedDirection===null,'시간 초과');});
  await test('누른 손가락·다중 터치·드래그·자동 클릭은 다음 문제로 이월 안 됨',async()=>{mount();const pad=fixture.querySelector('.reverse-pad');pad.setPointerCapture=()=>{};const pointer=(target,type,id)=>target.dispatchEvent(new PointerEvent(type,{bubbles:true,pointerId:id,button:0}));await until(()=>question(1));pointer(button('UP'),'pointerdown',1);await until(()=>question(2));pointer(button('DOWN'),'pointerdown',2);pointer(button('DOWN'),'pointermove',1);button('DOWN').dispatchEvent(new MouseEvent('click',{bubbles:true,detail:1}));assert(phase==='QUESTION'&&fixture.querySelector('#reverse-count').textContent==='1 / 10 성공','이월 입력');pointer(pad,'pointerup',1);pointer(button('DOWN'),'pointerdown',3);assert(phase==='FEEDBACK','새 터치');});
  await test('방향키 자동 반복·누른 키 무시 · 새 키 입력 인정',async()=>{mount();const key=(type,k,repeat=false)=>document.dispatchEvent(new KeyboardEvent(type,{key:k,bubbles:true,cancelable:true,repeat}));await until(()=>question(1));key('keydown','ArrowUp');await until(()=>question(2));key('keydown','ArrowUp',true);key('keydown','ArrowDown');assert(phase==='QUESTION'&&!settled,'중복 키');key('keyup','ArrowUp');key('keyup','ArrowDown');key('keydown','ArrowDown');key('keyup','ArrowDown');assert(phase==='FEEDBACK','새 키 미인정');});
  await test('360px 모바일 내부 너비 · 버튼 64px 이상 · 위치 고정',async()=>{mount();await until(()=>question(1));const before=E.DIRECTIONS.map(d=>button(d).getBoundingClientRect());assert(before.every(r=>r.width>=64&&r.height>=64),'터치 크기');assert(fixture.scrollWidth<=282,'넘침');click('UP');await until(()=>question(2));const after=E.DIRECTIONS.map(d=>button(d).getBoundingClientRect());assert(before.every((r,i)=>r.x===after[i].x&&r.y===after[i].y),'레이아웃 이동');});
  const store=new ProgressStore(`reverse-test-${MiniGames.uid()}`,TILE_CASES);await store.open();
  async function offer(){await store.update(g=>{g.data=TileState.fresh();g.data.status='minigame';g.data.cumulativeScore='1076';g.data.pendingMiniGame={...MiniGames.registry.get('reverse_tap').create(),type:'reverse_tap',miniGameId:'reverse',status:'OFFERED',payload:{questions}};});}
  await test('동시 시작과 동시 정산은 각각 한 번',async()=>{await offer();const results=await Promise.allSettled([store.update(g=>g.mini('start',{stake:'500',expectedBalance:'1076'},'a')),store.update(g=>g.mini('start',{stake:'500',expectedBalance:'1076'},'b'))]);assert(results.filter(r=>r.status==='fulfilled').length===1,'중복 차감');await store.update(g=>g.mini('running'));const s=new E.Session(questions);s.open(0);for(let i=0;i<10;i++){s.input(s.question.questionId,s.question.expectedDirection,s.questionStart+100);if(i<9)s.open(s.feedbackEnd);}await Promise.all([store.update(g=>g.mini('settle',s.result,'pay')),store.update(g=>g.mini('settle',s.result,'pay2'))]);const {model}=await store.update(()=>{});assert(model.data.cumulativeScore==='3076'&&model.data.miniGameHistory.length===1,'중복 지급');});
  await test('차감 저장 롤백 · 답변/피드백 중단 복구',async()=>{await offer();try{await store.update(g=>{g.mini('start',{stake:'500',expectedBalance:'1076'});g.data.invalid=()=>{};});}catch{}const restored=await store.update(()=>{});assert(restored.model.data.cumulativeScore==='1076','차감 롤백');for(const feedback of [false,true]){await offer();await store.update(g=>{g.mini('start',{stake:'500',expectedBalance:'1076'});g.mini('running');if(feedback)g.mini('feedback');});const {model}=await store.initialize();assert(model.data.cumulativeScore==='576'&&model.data.pendingMiniGame.result.multiplier===0,'중단 복구');}});
  store.db.close();indexedDB.deleteDatabase(store.name);fixture.innerHTML='';document.getElementById('summary').textContent=`${passed} passed · ${failed} failed`;
})();
