(function(root){
  'use strict';
  const CONFIG={rulesVersion:'reverse-v1',questionCount:10,answerLimitMs:1000,feedbackMs:250,countdownMs:3000,inputDrainMs:150,betStep:100,rewardTiers:[{min:10,multiplier:5},{min:7,multiplier:2},{min:5,multiplier:1},{min:0,multiplier:0}]};
  const DIRECTIONS=['UP','DOWN','LEFT','RIGHT'],OPPOSITE={UP:'DOWN',DOWN:'UP',LEFT:'RIGHT',RIGHT:'LEFT'},SYMBOL={UP:'↑',DOWN:'↓',LEFT:'←',RIGHT:'→'},LABEL={UP:'위',DOWN:'아래',LEFT:'왼쪽',RIGHT:'오른쪽'};
  function answer(mode,direction){if(!['SAME','OPPOSITE'].includes(mode)||!DIRECTIONS.includes(direction))throw Error('문제 규칙이 올바르지 않습니다.');return mode==='SAME'?direction:OPPOSITE[direction];}
  function questions(random=()=>crypto.getRandomValues(new Uint32Array(1))[0],config=CONFIG){return Array.from({length:config.questionCount},(_,i)=>{const mode=random()%2?'OPPOSITE':'SAME',direction=DIRECTIONS[random()%4];return {questionId:`q${i+1}`,mode,direction,expectedDirection:answer(mode,direction)};});}
  function validate(q,c=CONFIG){try{return Array.isArray(q)&&q.length===c.questionCount&&new Set(q.map(x=>x.questionId)).size===q.length&&q.every(x=>typeof x.questionId==='string'&&x.questionId.length>0&&x.expectedDirection===answer(x.mode,x.direction));}catch{return false;}}
  const multiplier=(k,c=CONFIG)=>c.rewardTiers.find(t=>k>=t.min).multiplier;
  function normalizeTimestamp(stamp,now,origin){let t=Number(stamp);if(t>1e12)t-=origin;return !Number.isFinite(t)||t<=0?now:Math.min(t,now);}
  class Session{
    constructor(q,c=CONFIG){if(!validate(q,c))throw Error('검증된 문제가 없습니다.');this.questions=structuredClone(q);this.config=structuredClone(c);this.phase='COUNTDOWN';this.correctCount=0;this.records=[];this.questionStart=null;this.feedbackEnd=null;this.result=null;}
    get question(){return this.questions[this.correctCount];}
    open(now){if(this.result||!['COUNTDOWN','FEEDBACK'].includes(this.phase)||this.phase==='FEEDBACK'&&now<this.feedbackEnd)return false;this.questionStart=now;this.phase='QUESTION';return true;}
    finish(reason){if(this.result)return this.result;const last=this.records.at(-1);this.phase='SETTLED';this.result={reason,correctCount:this.correctCount,failedQuestionId:['wrong','timeout'].includes(reason)?last.questionId:null,records:structuredClone(this.records)};return this.result;}
    input(questionId,direction,stamp,handledAt=stamp){if(this.result||this.phase!=='QUESTION'||questionId!==this.question.questionId||stamp<this.questionStart||!DIRECTIONS.includes(direction))return null;const responseMs=stamp-this.questionStart;if(responseMs>this.config.answerLimitMs)return this.timeout(stamp);const correct=direction===this.question.expectedDirection;this.records.push({questionId,selectedDirection:direction,responseMs,result:correct?'correct':'wrong'});if(!correct)return this.finish('wrong');this.correctCount++;if(this.correctCount===this.config.questionCount)return this.finish('complete');this.phase='FEEDBACK';this.feedbackEnd=handledAt+this.config.feedbackMs;return null;}
    timeout(now){if(this.result)return this.result;if(this.phase!=='QUESTION'||now<this.questionStart+this.config.answerLimitMs)return null;this.records.push({questionId:this.question.questionId,selectedDirection:null,responseMs:this.config.answerLimitMs,result:'timeout'});return this.finish('timeout');}
    interrupt(){return this.result||this.finish('interrupted');}
  }
  function judge(op,input){const q=op.payload.questions,c=op.config;if(!validate(q,c)||!['complete','wrong','timeout','interrupted'].includes(input.reason))throw Error('종료 기록이 올바르지 않습니다.');const records=input.records||[];if(!Array.isArray(records)||records.length>q.length)throw Error('응답 기록이 올바르지 않습니다.');let k=0,ended=null;
    for(let i=0;i<records.length;i++){const r=records[i],question=q[i];if(ended||r.questionId!==question.questionId||!Number.isFinite(r.responseMs)||r.responseMs<0||r.responseMs>c.answerLimitMs)throw Error('응답 기록 검증 실패');if(r.result==='timeout'){if(r.selectedDirection!==null||r.responseMs!==c.answerLimitMs)throw Error('시간 초과 기록 검증 실패');ended='timeout';}else{if(!DIRECTIONS.includes(r.selectedDirection))throw Error('선택 방향 검증 실패');const correct=r.selectedDirection===question.expectedDirection;if(r.result!==(correct?'correct':'wrong'))throw Error('정답 기록 검증 실패');if(correct){k++;if(k===q.length)ended='complete';}else ended='wrong';}}
    if(input.reason!=='interrupted'&&ended!==input.reason)throw Error('종료 사유 검증 실패');const failedQuestionId=['wrong','timeout'].includes(input.reason)?records.at(-1).questionId:null;return {correctCount:k,endReason:input.reason,failedQuestionId,records:structuredClone(records),multiplier:input.reason==='interrupted'?0:multiplier(k,c),oppositeCount:q.filter(x=>x.mode==='OPPOSITE').length,modeSwitchCount:q.slice(1).filter((x,i)=>x.mode!==q[i].mode).length,timing:input.timing||null};
  }
  const api={CONFIG,DIRECTIONS,OPPOSITE,SYMBOL,LABEL,answer,questions,validate,multiplier,normalizeTimestamp,Session,judge};if(typeof module!=='undefined')module.exports=api;else root.ReverseEngine=api;
})(globalThis);
