const assert=require('node:assert/strict'),E=require('./engine.js'),registry=require('../number-tiles/minigames/catalog.js'),{Game,fresh}=require('../number-tiles/state.js');require('../number-tiles/cases.js');let count=0;
const test=(n,f)=>{f();console.log('PASS',n);count++;};
const questions=Array.from({length:10},(_,i)=>{const mode=i%2?'OPPOSITE':'SAME',direction=E.DIRECTIONS[i%4];return {questionId:`q${i+1}`,mode,direction,expectedDirection:E.answer(mode,direction)};});
function session(){const s=new E.Session(questions);s.open(100);return s;}
function correct(s,response=100){return s.input(s.question.questionId,s.question.expectedDirection,s.questionStart+response);}
function play(k,reason='timeout'){const s=session();for(let n=0;n<k;n++){correct(s);if(s.phase==='FEEDBACK')s.open(s.feedbackEnd);}if(!s.result){if(reason==='wrong')s.input(s.question.questionId,E.OPPOSITE[s.question.expectedDirection],s.questionStart+100);else if(reason==='interrupted')s.interrupt();else s.timeout(s.questionStart+1000);}return s;}
function model(){const d=fresh(),plugin=registry.get('reverse_tap');d.status='minigame';d.cumulativeScore='1076';d.pendingMiniGame={...plugin.create(),type:plugin.type,miniGameId:'reverse-test',sourceRoundId:'round',status:'OFFERED',payload:{questions}};return new Game(globalThis.TILE_CASES,d,{recover:false});}
test('eight mappings and uniformly sampled independent questions',()=>{for(const dir of E.DIRECTIONS){assert.equal(E.answer('SAME',dir),dir);assert.equal(E.answer('OPPOSITE',dir),E.OPPOSITE[dir]);}for(let i=0;i<100;i++)assert(E.validate(E.questions()));for(let m=0;m<2;m++)for(let d=0;d<4;d++){let i=0;const q=E.questions(()=>i++%2?d:m);assert(q.every(x=>x.mode===(m?'OPPOSITE':'SAME')&&x.direction===E.DIRECTIONS[d]));}});
test('corrupted mapping, duplicate IDs and missing questions are rejected',()=>{for(const mutate of [q=>q.pop(),q=>q[0].expectedDirection='DOWN',q=>q[1].questionId=q[0].questionId]){const q=structuredClone(questions);mutate(q);assert(!E.validate(q));assert.throws(()=>new E.Session(q));}const g=model();g.data.pendingMiniGame.payload.questions[0].expectedDirection='DOWN';assert.throws(()=>g.mini('start',{stake:'500',expectedBalance:'1076'}));assert.equal(g.data.cumulativeScore,'1076');});
test('countdown and pre-render inputs are ignored',()=>{const s=new E.Session(questions);s.input('q1','UP',20);assert.equal(s.correctCount,0);s.open(100);s.input('q1','UP',99);assert.equal(s.correctCount,0);correct(s);assert.equal(s.correctCount,1);});
test('1000ms inclusive; 1001ms timeout has null choice',()=>{for(const t of [1000,1001]){const s=session();correct(s,t);assert.equal(s.correctCount,t===1000?1:0);if(t===1001){assert.equal(s.result.reason,'timeout');assert.equal(s.records[0].selectedDirection,null);}}const s=session();s.input('q1','UP',1100,1400);assert.equal(s.correctCount,1);assert.equal(s.feedbackEnd,1650);});
test('first wrong stays wrong, duplicate answers and feedback input ignored',()=>{const s=session();s.input('q1','DOWN',150);correct(s);assert.equal(s.result.reason,'wrong');assert.equal(s.records.length,1);const x=session();correct(x);x.input('q1','UP',220);x.input('q2','UP',230);assert.equal(x.correctCount,1);assert.equal(x.records.length,1);});
test('250ms feedback and stale previous-question events never carry forward',()=>{const s=session();correct(s);assert.equal(s.feedbackEnd,450);assert(!s.open(449.999));assert(s.open(450));assert.equal(s.questionStart,450);s.input('q1','UP',500);s.input('q2',s.question.expectedDirection,449);assert.equal(s.correctCount,1);correct(s,1000);assert.equal(s.correctCount,2);assert.equal(s.records[1].responseMs,1000);});
test('every success tier and both normal failure reasons',()=>{for(let k=0;k<=10;k++)for(const reason of ['wrong','timeout']){const s=play(k,reason),r=E.judge({payload:{questions},config:E.CONFIG},s.result);assert.equal(r.correctCount,k);assert.equal(r.multiplier,k===10?5:k>=7?2:k>=5?1:0);assert.equal(r.failedQuestionId,k===10?null:`q${k+1}`);if(k===10)assert.equal(s.records.length,10);}});
test('fabricated response records cannot grant payout',()=>{const op={payload:{questions},config:E.CONFIG};assert.throws(()=>E.judge(op,{reason:'complete',records:[]}));for(const patch of [{questionId:'q9'},{responseMs:1001},{selectedDirection:'DOWN'},{result:'timeout'}]){const s=play(10),input=structuredClone(s.result);Object.assign(input.records[0],patch);assert.throws(()=>E.judge(op,input));}});
test('shared wallet, large integer amounts and idempotent settlement',()=>{for(const k of [0,5,7,10]){const g=model();g.mini('start',{stake:'500',expectedBalance:'1076'},'debit');g.mini('start',{stake:'500',expectedBalance:'1076'},'debit');g.mini('running');assert.equal(g.data.pendingMiniGame.status,'QUESTION');const s=play(k);g.mini('settle',s.result,'pay');g.mini('settle',s.result,'pay-again');assert.equal(g.data.cumulativeScore,String(576+500*E.multiplier(k)));assert.equal(new Game(globalThis.TILE_CASES,g.data).data.miniGameHistory.length,1);}const g=model(),balance='900719925474099312345600';g.data.cumulativeScore=balance;g.mini('start',{stake:balance,expectedBalance:balance});g.mini('running');g.mini('settle',play(10).result);assert.equal(g.data.cumulativeScore,String(BigInt(balance)*5n));});
test('offered restoration, each active state recovery and interruption zero',()=>{const offered=model();assert.deepEqual(new Game(globalThis.TILE_CASES,offered.data).data.pendingMiniGame.payload.questions,questions);for(const phase of ['COUNTDOWN','QUESTION','FEEDBACK']){const g=model();g.mini('start',{stake:'1000',expectedBalance:'1076'});if(phase!=='COUNTDOWN')g.mini('running');if(phase==='FEEDBACK')g.mini('feedback');assert.equal(g.data.pendingMiniGame.status,phase);const recovered=new Game(globalThis.TILE_CASES,g.data);assert.equal(recovered.data.cumulativeScore,'76');assert.equal(recovered.data.pendingMiniGame.result.multiplier,0);assert.equal(new Game(globalThis.TILE_CASES,recovered.data).data.miniGameHistory.length,1);}assert.equal(E.judge({payload:{questions},config:E.CONFIG},play(7,'interrupted').result).multiplier,0);});
test('invalid bets and feedback transition guards',()=>{const g=model();for(const stake of ['0','99','150','1100'])assert.throws(()=>g.mini('start',{stake,expectedBalance:'1076'}));g.data.cumulativeScore='99';assert.throws(()=>g.mini('start',{stake:'100',expectedBalance:'99'}));g.data.cumulativeScore='1076';g.mini('start',{stake:'100',expectedBalance:'1076'});assert.throws(()=>g.mini('feedback'));g.mini('running');g.mini('feedback');assert.throws(()=>g.mini('settle',play(5).result));g.mini('question');assert.equal(g.data.pendingMiniGame.status,'QUESTION');});
test('five equal draws and final-stage skip/result paths',()=>{assert.deepEqual(registry.list().map(x=>x.weight),[1,1,1,1,1]);assert.deepEqual([0,.2,.4,.6,.8].map(r=>registry.draw(()=>r).type),['number_memory','dice_roll','timer_stop','reverse_tap','risky_vault']);for(const skip of [true,false]){const g=model();g.data.currentTarget=21;if(skip)g.mini('skip');else{g.mini('start',{stake:'100',expectedBalance:'1076'});g.mini('running');g.mini('settle',play(10).result);}g.next();assert.equal(g.data.status,'finished');}});
console.log(`${count} reverse suites passed`);
