'use strict';
const E=TileEngine,$=id=>document.getElementById(id),num=n=>BigInt(typeof n==='number'?Math.floor(n):n).toLocaleString('ko-KR');
const dbName=new URLSearchParams(location.search).has('test')?'chagok-prototype-v1':'chagok-v1';
let game,store,miniHost,busy=false,writes=0,owner=false,startedAt=0,pausedMs=0,countToken=0,noticeTimer,storageFailed=false;
const instructions={1:'숫자 → 연산자 → 숫자 순서로 터치하세요. 목표와 같으면 수식 확정! 더 만들 수 없을 때 완료를 눌러요.',2:'잘못 골랐다면 ↶로 한 칸 되돌리세요. 같은 숫자라도 서로 다른 타일이면 각각 사용할 수 있어요.',3:'처음부터 답이 없는 판도 있어요. 그럴 땐 ‘불가능’을 누르세요. 만들 수 있는 수식이 있다면 감점돼요.',4:'숫자 3개부터 콤보 보너스! ×와 ÷를 먼저 계산해요. 괄호나 숫자 이어 붙이기는 사용할 수 없어요.',11:'타일이 12개로 늘어나요. 위치에 상관없이 자유롭게 연결해 보세요.',16:'이번부터 16개 타일! 긴 수식과 빠른 판단 사이에서 나만의 전략을 찾아보세요.'};
function elapsed(){return Math.max(0,(performance.now()-startedAt-pausedMs)/1000);}
function tell(message,error=false){$('notice').textContent=message;$('notice').classList.toggle('error',error);clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>{$('notice').textContent='';},6000);}
async function commit(fn,selection=[]){if(!owner)throw Error('다른 탭에서 진행 중입니다.');writes++;busy=true;const began=performance.now(),wasPlaying=game?.data.status==='playing';try{const saved=await store.update(fn,selection);game=saved.model;$('save-status').textContent='로컬 자동 저장';return saved;}catch(e){$('save-status').textContent='저장 실패 · 다시 시도 가능';throw e;}finally{if(wasPlaying&&game?.data.status==='playing')pausedMs+=performance.now()-began;writes--;busy=writes>0;render();}}
async function action(fn){if(busy||storageFailed||!owner)return false;try{return await commit(fn,game?.selected||[]);}catch(e){tell(`저장하지 못했어요. ${e.message}`,true);console.error(e);return false;}}
function chrome(){const d=game.data,target=['result','minigame'].includes(d.status)?d.result.target:Math.min(20,d.currentTarget);$('stage').textContent=String(target).padStart(2,'0');$('score').textContent=num(d.cumulativeScore);$('progress').style.width=`${d.history.length/20*100}%`;$('journey').innerHTML=Array.from({length:20},(_,i)=>`<span class="${i<d.history.length?'done':i+1===target?'current':''}">${i<d.history.length?'✓':String(i+1).padStart(2,'0')}</span>`).join('');}
function targetHTML(t){return `<div class="target"><div class="eyebrow">MAKE THIS NUMBER</div><div class="target-value">${t}</div><p>타일을 연결해 목표 숫자를 만들어 보세요</p></div>`;}
function render(){if(!game||!owner)return;chrome();const d=game.data,isMini=d.status==='minigame';document.body.classList.toggle('in-minigame',isMini);const miniActive=['COUNTDOWN','RUNNING','MEMORIZE','RECALL','QUESTION','FEEDBACK','SELECTING','REVEALING','DECIDING'].includes(d.pendingMiniGame?.status);$('help').disabled=miniActive;$('settings').disabled=miniActive;if(isMini){miniHost.show();return;}miniHost?.dispose();if(d.status==='ready')renderReady();else if(d.status==='playing')renderPlay();else if(d.status==='result')renderResult();else if(d.status==='finished')renderFinished();}
function renderReady(){const d=game.data,t=d.currentTarget;$('screen').innerHTML=`<div class="ready"><span class="ready-badge">${t<=10?'WARM UP':t<=15?'FIND YOUR FLOW':'A LITTLE DEEPER'} · ${E.band(t).tiles} TILES</span><h2>${d.round.restarts?'다시, 차곡차곡.':t===1?'작은 몰입을 시작할까요?':`다음 목표, 숫자 ${t}.`}</h2><p>목표 숫자 <strong>${t}</strong> · ${E.band(t).tiles}개의 타일<br>시작하면 타일과 타이머가 함께 열려요.</p><div class="sealed-board" aria-label="시작 전에는 타일이 숨겨져 있습니다">${Array.from({length:9},()=>'<span>·</span>').join('')}</div><div class="instruction">${instructions[t]||'타일을 자유롭게 연결하세요. 정답을 만든 후 남은 해답이 없다면 완료! 긴 수식에는 콤보 보상이 있어요.'}${d.round.restarts?'<br>중단한 판의 임시 보상은 초기화되고, 적용된 감점은 유지돼요.':''}</div><button class="primary" id="start">${d.round.restarts?'다시 시작':t===1?'플레이 시작':'이번 판 시작'} <span>→</span></button><small>시간 감점 ${E.band(t).rate}점/초 · 누적 점수는 줄어들지 않아요</small></div>`;$('start').onclick=begin;}
async function begin(){if(busy||storageFailed)return;if(!await action(g=>g.prepare()))return;if(game.data.status!=='countdown')return;if(document.hidden){interrupt('hidden_before_start');return;}const token=++countToken;for(let n=3;n>0;n--){if(token!==countToken||game.data.status!=='countdown')return;$('screen').innerHTML=`<div class="countdown"><p>목표 ${game.data.currentTarget}, 준비됐나요?</p><b>${n}</b><p>숫자 사이에서 나만의 답을 찾아보세요.</p></div>`;await new Promise(r=>setTimeout(r,600));}if(token!==countToken||game.data.status!=='countdown')return;await action(g=>g.start());startedAt=performance.now();pausedMs=0;render();}
function renderPlay(){const d=game.data,a=d.attempt,c=game.case,selected=game.selected,ready=selected.length>=3&&selected.length%2===1;$('screen').innerHTML=`${targetHTML(d.currentTarget)}<div class="stats"><span>이번 판 예상 <b id="estimate">0</b></span><span>경과 시간 <b class="time" id="timer">00:00</b></span></div><div class="expression-wrap"><div id="expression" class="expression ${selected.length?'':'empty'}">${selected.length?selected.map(i=>c.values[i]).join(' '):'숫자 타일부터 선택해 주세요'}</div><button id="undo" aria-label="마지막 선택 되돌리기" ${selected.length?'':'disabled'}>↶</button></div><div class="selection-tools"><span>${a.solvedExpressions.length?`정답 ${a.solvedExpressions.length}개 · 임시 보상 +${num(E.reward(d.currentTarget,0,a.solvedExpressions,false).expression+E.reward(d.currentTarget,0,a.solvedExpressions,false).combo)}`:'숫자와 연산자를 번갈아 선택해요'}</span><button id="clear" ${selected.length?'':'disabled'}>선택 지우기</button></div><div class="tiles ${c.values.length===16?'four':''}">${a.layout.map(i=>{const v=c.values[i],order=selected.indexOf(i),removed=!(a.remainingMask&(1<<i));return `<button class="tile ${typeof v==='number'?'':'op'} ${order>=0?'selected':''} ${removed?'removed':''}" data-tile="${i}" aria-label="${v} 타일${order>=0?`, ${order+1}번째 선택`:''}" aria-pressed="${order>=0}" ${removed||order>=0?'disabled':''}>${v}${order>=0?`<span class="order">${order+1}</span>`:''}</button>`;}).join('')}</div><button class="primary" id="submit" ${ready?'':'disabled'}>수식 확정 <span>↵</span></button><div class="end-actions"><button id="impossible" ${a.solvedExpressions.length?'disabled':''}>∅ &nbsp; 불가능</button><button id="complete" class="complete" ${a.solvedExpressions.length?'':'disabled'}>완료 &nbsp; ✓</button></div>`;
  document.querySelectorAll('[data-tile]').forEach(b=>b.onclick=()=>{if(busy)return;if(!game.select(Number(b.dataset.tile))){tell(selected.length%2===0?'숫자 타일을 선택해 주세요.':'연산자 타일을 선택해 주세요.');return;}renderPlay();});
  $('undo').onclick=()=>{if(!busy){game.undo();renderPlay();}};$('clear').onclick=()=>{if(!busy){game.clear();renderPlay();}};
  $('submit').onclick=async()=>{const saved=await action(g=>g.submit());if(saved){const r=saved.result;tell(r.ok?`${r.expression.numbers>=3?'콤보! ':''}정답이에요. +${num(r.points)}점 임시 적립`:r.message,!r.ok);}};
  $('impossible').onclick=()=>declare('impossible');$('complete').onclick=()=>declare('complete');const field=$('expression');field.scrollLeft=field.scrollWidth;tick();
}
async function declare(kind){const seconds=elapsed(),saved=await action(g=>g.declare(kind,seconds));if(!saved||saved.result.ignored)return;const r=saved.result;if(!r.ok)tell(`만들 수 있는 수식이 남아 있어요. −${num(r.penalty)}점${r.penalty<r.requested?' (누적 점수 최저 0점)':''}`,true);else tell('이번 판 보상과 미니게임 기회가 저장됐어요.');}
function renderResult(){const r=game.data.result;$('screen').innerHTML=`<div class="result"><div class="result-mark">${r.kind==='impossible'?'∅':'✓'}</div><div class="eyebrow">STAGE ${String(r.target).padStart(2,'0')} CLEAR</div><h2>${r.kind==='impossible'?'정확한 판단이에요!':'차곡차곡, 해냈어요.'}</h2><p>${r.kind==='impossible'?'처음부터 가능한 수식이 없는 판이었어요.':`${r.expressions}개의 수식을 완성했어요.`} · ${r.seconds.toFixed(1)}초</p><div class="result-score">+${num(r.total)}</div><small>이번 판 확정 보상</small><div class="result-list"><div><span>클리어 기본점수</span><b>+${num(r.base)}</b></div><div><span>시간 감점</span><b>−${num(r.timePenalty)}</b></div><div><span>수식 보상</span><b>+${num(r.expression)}</b></div><div><span>콤보 보상</span><b>+${num(r.combo)}</b></div><div><span>불가능 보너스</span><b>+${num(r.bonus)}</b></div><div><span>이미 적용된 실제 오판 감점</span><b>−${num(r.penalty)}</b></div><div class="sum"><span>이번 단계 순증감</span><b>${r.net>=0?'+':'−'}${num(BigInt(r.net)<0n?-BigInt(r.net):BigInt(r.net))}</b></div></div><button class="primary" id="next">${game.data.pendingMiniGame?'미니게임 도전':r.target===20?'전체 결과 보기':'다음 목표로'} <span>→</span></button></div>`;$('next').onclick=()=>action(g=>g.next());}
function renderFinished(){const d=game.data;$('screen').innerHTML=`<div class="result"><div class="result-mark">✳</div><div class="eyebrow">YOUR JOURNEY IS COMPLETE</div><h2>20번의 목표, 모두 완성.</h2><p>프로토타입을 끝까지 플레이해 주셔서 감사해요.<br>당신의 작은 몰입이 차곡차곡 쌓였어요.</p><div class="result-score">${num(d.cumulativeScore)}</div><small>수식 게임 + 미니게임 최종 누적 점수</small><div class="result-list"><div><span>완료한 단계</span><b>20 / 20</b></div><div><span>완성한 수식</span><b>${d.history.reduce((s,r)=>s+r.expressions,0)}개</b></div><div><span>클리어한 시도의 플레이 시간</span><b>${Math.round(d.history.reduce((s,r)=>s+r.seconds,0))}초</b></div><div><span>받은 콤보 보상</span><b>${num(d.history.reduce((s,r)=>s+r.combo,0))}점</b></div></div><div class="result-list"><div><span>미니게임 참여</span><b>${d.miniGameHistory.filter(o=>o.status==='SETTLED').length}회</b></div><div><span>미니게임 순증감 합계</span><b>${num(d.miniGameHistory.reduce((s,o)=>s+BigInt(o.result?.netChange||0),0n))}점</b></div></div><p>기록은 이 브라우저에 보관돼요.<br>다음에 방문해도 이 결과를 확인할 수 있어요.</p><button class="primary" id="export-final">플레이 기록 내보내기 <span>↗</span></button><button class="secondary" id="finish-close">종료 · 결과 보관</button></div>`;$('export-final').onclick=exportData;$('finish-close').onclick=()=>tell('결과가 보관돼 있어요. 이제 이 탭을 닫아도 돼요.');}
function tick(){if(game?.data.status!=='playing')return;const seconds=elapsed(),a=game.data.attempt,estimate=E.reward(game.data.currentTarget,seconds,a.solvedExpressions,false);if($('estimate'))$('estimate').textContent=`+${num(estimate.total)}`;if($('timer'))$('timer').textContent=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(Math.floor(seconds%60)).padStart(2,'0')}`;}
function openDialog(html){$('dialog-content').innerHTML=html;$('dialog').showModal();}
$('help').onclick=()=>{if(game?.data.status==='playing'||game?.data.status==='countdown'){tell('진행 중에도 시간은 흐릅니다. 안내는 다음 판 시작 전에 확인해 주세요.');return;}openDialog('<div class="eyebrow">HOW TO PLAY</div><h2>숫자를 잇는 세 가지 규칙</h2><ul><li>숫자와 연산자를 번갈아 눌러 목표 숫자를 만드세요. 숫자는 2개 이상 필요해요.</li><li>×, ÷를 먼저 계산해요. 같은 값의 타일도 각각 사용할 수 있어요.</li><li>수식 확정으로 타일을 제거한 뒤, 더 만들 수 없으면 <b>완료</b>를 누르세요.</li><li>처음부터 답이 없다면 <b>불가능</b>. 오판하면 기본점수의 20%가 감점돼요.</li><li>숫자 3개부터 콤보 보상! 시간 감점은 이번 판 기본점수에만 적용돼요.</li></ul><p>다른 탭으로 이동하거나 화면을 잠그면 현재 판은 중단돼요. 돌아오면 같은 목표의 다른 문제로 다시 시작해요.</p><p>이 브라우저에만 저장되며, 브라우저 데이터를 삭제하면 진행 기록도 사라져요.</p>');};
$('close-dialog').onclick=()=>$('dialog').close();
function exportData(){if(!game)return;const data={exportedAt:new Date().toISOString(),config:E.CONFIG,progress:game.data};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download='chagok-playtest.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('settings').onclick=()=>{if(!game)return;if(['playing','countdown'].includes(game.data.status)){tell('개발 메뉴는 판 시작 전이나 결과 화면에서 열 수 있어요.');return;}openDialog(`<div class="eyebrow">PLAYTEST TOOLS</div><h2>개발 메뉴</h2><p>검증된 문제 ${game.cases.length}개 · 목표 1–20<br>기록과 점수는 이 브라우저에만 저장돼요.</p><button class="secondary" id="export">플레이 기록 JSON 내보내기</button><button class="secondary danger" id="reset">전체 진행 초기화</button><div class="settings-info">밸런스는 engine.js의 CONFIG에서 변경할 수 있어요.<br>문제 생성·검증은 build-cases.cjs로 실행해요.</div><div id="reset-confirm"></div>`);$('export').onclick=exportData;$('reset').onclick=()=>{$('reset-confirm').innerHTML='<p>누적 점수와 모든 플레이 기록이 삭제돼요.</p><button class="primary" id="confirm-reset">기록 삭제하고 1단계부터</button>';$('confirm-reset').onclick=async()=>{if(busy)return;$('dialog').close();await action(g=>{g.data=TileState.fresh();g.selected=[];});tell('1단계부터 새로 시작해요.');};};};
function interrupt(reason){countToken++;if(!game||!owner)return;if(game.data.status==='minigame'){miniHost.interrupt();return;}if(['playing','countdown'].includes(game.data.status))commit(g=>g.interrupt(reason)).then(()=>tell('판이 중단됐어요. 같은 목표의 다른 문제로 다시 시작해요.')).catch(()=>{});}
document.addEventListener('visibilitychange',()=>{if(document.hidden)interrupt('visibility_hidden');});
window.addEventListener('pagehide',()=>{interrupt('pagehide');if(store?.leaseId)store.lease('release').catch(()=>{});});
window.addEventListener('pageshow',e=>{if(e.persisted)location.reload();});
document.addEventListener('keydown',e=>{if($('dialog').open||game?.data.status!=='playing'||busy)return;if(e.key==='Backspace'){e.preventDefault();game.undo();renderPlay();}else if(e.key==='Enter'&&$('submit')&&!$('submit').disabled){e.preventDefault();$('submit').click();}});
function blocked(message){$('screen').innerHTML=`<div class="ready"><h2>진행을 확인하고 있어요.</h2><p>${message}</p><button class="primary" onclick="location.reload()">다시 연결</button></div>`;$('save-status').textContent='연결 대기';}
async function connect(){owner=true;const saved=await store.initialize();game=saved.model;miniHost=new MiniGameHost({container:$('screen'),getData:()=>game.data,command:(type,payload,eventId)=>commit(g=>g.mini(type,payload,eventId)),next:()=>action(g=>g.next()),notice:tell});render();setInterval(tick,100);}
async function init(){try{
  store=new ProgressStore(dbName,TILE_CASES);await store.open(()=>blocked('이전 버전의 본게임 탭을 닫아 주세요.<br>점수와 진행을 보존해 새 버전으로 연결합니다.'));
  if(navigator.locks){navigator.locks.request(`${dbName}-owner`,{ifAvailable:true},async lock=>{if(!lock){blocked('다른 본게임 탭에서 진행 중이에요.<br>한 탭에서만 플레이할 수 있습니다.');return;}await connect();await new Promise(()=>{});}).catch(e=>{console.error(e);blocked('저장 공간 연결에 실패했어요. 다시 시도해 주세요.');});return;}
  const acquire=async()=>{if(!await store.lease()){blocked('다른 게임 탭을 닫아 주세요.<br>잠시 후 자동으로 다시 연결합니다.');setTimeout(()=>acquire().catch(fail),2000);return;}await connect();const heartbeat=setInterval(async()=>{try{if(await store.lease('renew'))return;}catch{}clearInterval(heartbeat);owner=false;countToken++;miniHost?.dispose();blocked('연결이 잠시 끊겼어요.<br>다시 연결을 눌러 진행을 복원해 주세요.');},4000);};
  await acquire();
}catch(e){fail(e);}}
function fail(e){console.error(e);owner=false;blocked('저장 공간을 열지 못했어요. 일반 브라우저 창에서 다시 시도해 주세요.');}
init();





