MiniGames.registry.get('risky_vault').weight=0; // Timer-only regression fixture.
MiniGames.registry.get('reverse_tap').weight=0; // Timer-only regression fixture.
MiniGames.registry.get('number_memory').weight=0; // Timer-only regression fixture.
MiniGames.registry.get('dice_roll').weight=0; // Timer-specific regression fixtures.
(async()=>{const store=new ProgressStore(`chagok-integration-${MiniGames.uid()}`,TILE_CASES);await store.open();let count=0,failed=0;const assert=(v,msg)=>{if(!v)throw Error(msg);};async function test(name,fn){const li=document.createElement('li');try{await fn();count++;li.textContent=`PASS ${name}`;}catch(e){failed++;li.className='fail';li.textContent=`FAIL ${name}: ${e.message}`;}document.getElementById('results').append(li);}
  async function offer(){await store.update(g=>{g.data=TileState.fresh();g.data.currentTarget=3;g.data.round.target=3;g.prepare();g.start();g.declare('impossible',5);g.next();});}
  await test('수식 보상과 기회 생성은 같은 트랜잭션으로 롤백됨',async()=>{await store.initialize();await store.update(g=>{g.data.currentTarget=3;g.data.round.target=3;g.prepare();g.start();});let rejected=false;try{await store.update(g=>{g.declare('impossible',5);g.data.invalid=()=>{};});}catch{rejected=true;}const {model}=await store.update(()=>{});assert(rejected,'실패 미감지');assert(model.data.cumulativeScore==='0'&&model.data.pendingMiniGame===null&&model.data.status==='playing','부분 반영');});
  await test('동시 베팅 요청은 한 번만 차감',async()=>{await offer();const results=await Promise.allSettled([store.update(g=>g.mini('start',{stake:'500',expectedBalance:'1200'},'a')),store.update(g=>g.mini('start',{stake:'500',expectedBalance:'1200'},'b'))]);assert(results.filter(r=>r.status==='fulfilled').length===1,'중복 시작');const {model}=await store.update(()=>{});assert(model.data.cumulativeScore==='700','중복 차감');});
  await test('시작 저장 실패 시 점수와 기회 모두 복원',async()=>{await offer();try{await store.update(g=>{g.mini('start',{stake:'500',expectedBalance:'1200'});g.data.invalid=()=>{};});}catch{}const {model}=await store.update(()=>{});assert(model.data.cumulativeScore==='1200'&&model.data.pendingMiniGame.status==='OFFERED','차감 누출');});
  await test('정지 저장 실패 후 동일 이벤트 재시도 및 동시 정산은 지급 한 번',async()=>{await offer();await store.update(g=>g.mini('start',{stake:'500',expectedBalance:'1200'}));await store.update(g=>g.mini('running'));const settle=g=>g.mini('settle',{reason:'stopped',elapsedMs:g.data.pendingMiniGame.payload.targetMs},'result');try{await store.update(g=>{settle(g);g.data.invalid=()=>{};});}catch{}const before=await store.update(()=>{});assert(before.model.data.cumulativeScore==='700','실패한 지급 반영');await Promise.all([store.update(settle),store.update(settle)]);const after=await store.update(()=>{});assert(after.model.data.cumulativeScore==='2200'&&after.model.data.miniGameHistory.length===1,'중복 지급');});
  await test('20단계 뒤 건너뛰고 전체 종료',async()=>{await store.update(g=>{g.data=TileState.fresh();g.data.currentTarget=20;g.data.round.target=20;g.prepare();g.start();let i;while((i=g.case.solutionMasks.findIndex(s=>(s&g.data.attempt.remainingMask)===s))>=0){g.case.witnessExpressions[i].forEach(id=>g.select(id));g.submit();}g.declare(g.data.attempt.solvedExpressions.length?'complete':'impossible',5);g.next();});await store.update(g=>g.mini('skip'));const {model}=await store.update(g=>g.next());assert(model.data.status==='finished'&&model.data.currentTarget===21,'완료 경로 오류');});
  await test('HTTP 모바일 잠금: 두 탭 중 한 탭만 소유권 획득',async()=>{const other=new ProgressStore(store.name,TILE_CASES);await other.open();assert(await store.lease(),'첫 소유권 실패');assert(!await other.lease(),'중복 소유권');assert(await store.lease('renew'),'갱신 실패');await other.lease('release');assert(await store.lease('renew'),'타인의 잠금 해제');other.db.close();});
  await test('HTTP 모바일 잠금: 만료 후 새 소유자만 쓰기 가능',async()=>{const other=new ProgressStore(store.name,TILE_CASES);await other.open();assert(await other.lease('acquire',Date.now()+13000),'만료 후 인계 실패');let rejected=false;try{await store.update(g=>{g.data.cumulativeScore='999';});}catch{rejected=true;}assert(rejected,'오래된 탭이 점수를 변경함');const result=await other.update(()=>{});assert(result.model.data.cumulativeScore!=='999','이전 탭 변경 누출');await other.lease('release');other.db.close();});
  document.getElementById('summary').textContent=`${count} passed · ${failed} failed`;store.db.close();indexedDB.deleteDatabase(store.name);
})();


