const fs=require('node:fs');
const E=require('./engine.js');
const cases=[];const started=performance.now();
for(let target=1;target<=20;target++){
  const count=E.band(target).tiles;
  for(let variant=0;variant<6;variant++){
    let values;
    if(variant<4){
      const a=variant+2;
      const operators=['−',variant%2?'÷':'+','×',...(count>9?['+']:[])];
      const numbers=[target+a,a,1,2,3,4,6,8,2,5,1,3,7].slice(0,count-operators.length);
      values=[...numbers,...operators];
    }else{
      const unit=(target+1)*(variant-3),operators=['+','−','×',...(count>9?['+']:[])];
      values=[...Array.from({length:count-operators.length},(_,i)=>unit*(1+(i+variant)%3)),...operators];
    }
    if(variant===0&&target===1)values=[3,'+',8,'÷',5,2,8,'−',4];
    if(variant===0&&target===2)values=[6,'×',3,2,'−',5,'÷',4,3];
    if(variant===4&&target===3)values=[2,'+',8,'×',4,2,6,'−',4];
    const t=performance.now(),data=E.solve(values,target);
    const c={caseId:`t${target}-v${variant}`,target,values,difficultyBand:count,isImpossible:data.solutionMasks.length===0,...data,rulesVersion:E.RULES_VERSION,contentHash:E.hash(values)};
    if(c.isImpossible!==(variant>=4))throw Error(`Invalid case ${c.caseId}`);
    cases.push(c);
    if(target===20)console.log(c.caseId,`${Math.round(performance.now()-t)}ms`,`${data.verification.visited} sequences`,`${data.solutionMasks.length} masks`);
  }
}
fs.writeFileSync(__dirname+'/cases.js','/* Generated by build-cases.cjs. Exhaustively verified; do not hand-edit. */\nglobalThis.TILE_CASES='+JSON.stringify(cases)+';\n');
console.log(`Verified ${cases.length} cases in ${((performance.now()-started)/1000).toFixed(2)}s`);
