require('./minigames/catalog.js').get('reverse_tap').weight=0; // Timer-only regression fixture.
require('./minigames/catalog.js').get('number_memory').weight=0; // Timer-only regression fixture.
const assert=require('node:assert/strict'),{Game,fresh,migrate}=require('./state.js'),{Registry}=require('./minigames/registry.js');
require('./minigames/catalog.js').get('dice_roll').weight=0; // Timer-specific regression fixtures.
require('./cases.js');const cases=globalThis.TILE_CASES;let count=0;
const test=(name,fn)=>{fn();count++;console.log('PASS',name);};
function cleared(target=3){const d=fresh();d.currentTarget=target;d.round.target=target;const g=new Game(cases,d);g.prepare();g.start();let i;while((i=g.case.solutionMasks.findIndex(s=>(s&g.data.attempt.remainingMask)===s))>=0){g.case.witnessExpressions[i].forEach(id=>g.select(id));assert.ok(g.submit().ok);}g.declare(g.data.attempt.solvedExpressions.length?'complete':'impossible',5);return g;}
test('normal and impossible clear create exactly one persisted opportunity, no reroll',()=>{for(const target of [1,3]){const g=cleared(target),o=structuredClone(g.data.pendingMiniGame);assert.equal(o.type,'timer_stop');assert.equal(o.sourceRoundId,g.data.result.roundId);assert.equal(g.data.pendingMiniGameId,o.miniGameId);g.declare('impossible',5);assert.deepEqual(g.data.pendingMiniGame,o);const restored=new Game(cases,g.data);assert.deepEqual(restored.data.pendingMiniGame,o);g.next();assert.equal(g.data.status,'minigame');g.next();assert.equal(g.data.status,'minigame');g.prepare();assert.equal(g.data.status,'minigame');}});
test('wrong declaration and interrupted tile attempt never create a mini game',()=>{const g=new Game(cases);g.prepare();g.start();g.declare('impossible',1);assert.equal(g.data.pendingMiniGame,null);g.interrupt('test');assert.equal(g.data.pendingMiniGame,null);});
test('shared wallet debits once, 3x returns principal, restored result never pays twice',()=>{const g=cleared();g.next();const before=BigInt(g.data.cumulativeScore),id='unique-start';g.mini('start',{stake:'500',expectedBalance:String(before)},id);g.mini('start',{stake:'500',expectedBalance:String(before)},id);assert.equal(g.data.cumulativeScore,String(before-500n));assert.throws(()=>g.mini('start',{stake:'500',expectedBalance:String(before)}));g.mini('running');g.mini('settle',{reason:'stopped',elapsedMs:g.data.pendingMiniGame.payload.targetMs},'unique-result');g.mini('settle',{reason:'stopped',elapsedMs:0},'other-result');assert.equal(g.data.cumulativeScore,String(before+1000n));assert.equal(g.data.miniGameHistory.length,1);const restored=new Game(cases,g.data);assert.equal(restored.data.cumulativeScore,String(before+1000n));restored.next();assert.equal(restored.data.status,'ready');assert.equal(restored.data.currentTarget,4);assert.equal(restored.data.pendingMiniGame,null);});
test('countdown and running restore lose stake once and preserve stage advancement',()=>{for(const running of [false,true]){const g=cleared();g.next();const before=BigInt(g.data.cumulativeScore);g.mini('start',{stake:'100',expectedBalance:String(before)});if(running)g.mini('running');const restored=new Game(cases,g.data);assert.equal(restored.data.pendingMiniGame.status,'SETTLED');assert.equal(restored.data.pendingMiniGame.result.endReason,'interrupted');assert.equal(restored.data.cumulativeScore,String(before-100n));const twice=new Game(cases,restored.data);assert.equal(twice.data.cumulativeScore,restored.data.cumulativeScore);assert.equal(twice.data.miniGameHistory.length,1);twice.next();assert.equal(twice.data.currentTarget,4);}});
test('20th stage must finish or skip mini game before full completion',()=>{for(const skip of [true,false]){const g=cleared(20);assert.equal(g.data.currentTarget,21);g.next();assert.equal(g.data.status,'minigame');g.next();assert.equal(g.data.status,'minigame');if(skip)g.mini('skip');else{g.mini('start',{stake:'100',expectedBalance:g.data.cumulativeScore});g.mini('running');g.mini('settle',{reason:'stopped',elapsedMs:g.data.pendingMiniGame.payload.targetMs});}g.next();assert.equal(g.data.status,'finished');assert.equal(g.data.currentTarget,21);const balance=g.data.cumulativeScore;g.next();g.prepare();assert.equal(g.data.cumulativeScore,balance);assert.equal(g.data.status,'finished');}});
test('insufficient and zero scores may skip; oversized, stale, and fractional bets fail',()=>{const g=cleared();g.next();g.data.cumulativeScore='99';for(const stake of ['0','100','150','100.1'])assert.throws(()=>g.mini('start',{stake,expectedBalance:'99'}));g.mini('skip');assert.equal(g.data.cumulativeScore,'99');g.next();assert.equal(g.data.status,'ready');});
test('v1 migration preserves stage/score and old finished campaigns; result migration creates one opportunity',()=>{const d=fresh();d.schemaVersion=1;d.cumulativeScore=123456;d.round.accumulatedActualPenalty=200;delete d.pendingMiniGame;delete d.pendingMiniGameId;delete d.miniGameHistory;const n=migrate(d);assert.equal(n.cumulativeScore,'123456');assert.equal(n.round.accumulatedActualPenalty,'200');assert.equal(n.status,'ready');assert.equal(n.pendingMiniGame,null);const result=cleared().data;result.schemaVersion=1;result.pendingMiniGame=null;result.pendingMiniGameId=null;const migrated=migrate(result);assert.ok(migrated.pendingMiniGame);assert.equal(migrate(migrated).pendingMiniGameId,migrated.pendingMiniGameId);d.status='finished';d.currentTarget=21;assert.equal(migrate(d).pendingMiniGame,null);});
test('weighted registry selects all registered types and old disabled games remain loadable',()=>{const r=new Registry();for(const [type,weight]of [['a',1],['b',3],['old',0]])r.register({type,title:type,weight,create:()=>({rulesVersion:'test',config:{betStep:100},payload:{}}),judge:()=>({multiplier:1,endReason:'stopped'})});assert.equal(r.draw(()=>0).type,'a');assert.equal(r.draw(()=>.24999).type,'a');assert.equal(r.draw(()=>.25).type,'b');assert.equal(r.draw(()=>.9999).type,'b');assert.equal(r.get('old').weight,0);assert.equal(r.create('round',()=>.5).type,'b');});
test('a second game plugs into shared settlement without changing Game or wallet',()=>{const r=new Registry();r.register({type:'future-game-test',title:'테스트 게임',weight:1,create:()=>({rulesVersion:'test',config:{betStep:100},payload:{answer:7}}),judge:(o,input)=>({multiplier:input.answer===o.payload.answer?4:0,endReason:'stopped'})});const d=fresh();d.currentTarget=3;d.round.target=3;const g=new Game(cases,d,{registry:r});g.prepare();g.start();g.declare('impossible',1);assert.equal(g.data.pendingMiniGame.type,'future-game-test');g.next();const before=BigInt(g.data.cumulativeScore);g.mini('start',{stake:'100',expectedBalance:String(before)});g.mini('running');g.mini('settle',{answer:7});assert.equal(g.data.cumulativeScore,String(before+300n));});
test('arbitrarily large shared scores remain exact through mini payout and tile penalty',()=>{const g=cleared();g.next();g.data.cumulativeScore='900719925474099312345678976';const before=BigInt(g.data.cumulativeScore),stake=String(before/100n*100n);g.mini('start',{stake,expectedBalance:String(before)});g.mini('running');g.mini('settle',{reason:'stopped',elapsedMs:g.data.pendingMiniGame.payload.targetMs});assert.equal(g.data.cumulativeScore,String(before+BigInt(stake)*2n));g.next();g.prepare();g.start();if(!g.case.isImpossible){const score=BigInt(g.data.cumulativeScore);g.declare('impossible',1);assert.equal(g.data.cumulativeScore,String(score-200n));}assert.equal(JSON.parse(JSON.stringify(g.data)).cumulativeScore,g.data.cumulativeScore);});
console.log(`${count} integration suites passed`);

