const assert=require('node:assert/strict'),E=require('./engine.js'),{Game,fresh}=require('./state.js');
require('./cases.js');const cases=globalThis.TILE_CASES;let total=0;
function test(name,fn){fn();total++;console.log('PASS',name);}
function round(target=1){const d=fresh();d.currentTarget=target;d.round.target=target;const g=new Game(cases,d);g.prepare();g.start();return g;}
function enter(g,values){for(const value of values){const i=g.case.values.findIndex((v,i)=>v===value&&(g.data.attempt.remainingMask&(1<<i))&&!g.selected.includes(i));assert.ok(g.select(i));}return g.submit();}
test('A03 A05 exact precedence, left associativity, fractional and negative intermediate values',()=>{for(const [v,result] of [[[2,'+',3,'×',4],14],[[8,'÷',4,'×',2],4],[[1,'÷',3,'×',3],1],[[1,'−',3,'+',4],2],[[1,'−',3,'×',2],-5],[[1,'÷',3,'+',2,'÷',3],1]])assert.ok(E.equal(E.evaluate(v),result));});
test('A04 invalid grammar and zero division',()=>{for(const v of [[1],[1,2,3],[1,'+', '+'],[1,'÷',0],[1,'+',2,'×']])assert.throws(()=>E.evaluate(v));});
test('A01 A02 A06 A07 A08 input, distinct duplicates, explicit confirmation, removal and clear',()=>{const g=round();assert.ok(g.select(0));assert.equal(g.select(0),false);assert.equal(g.select(2),false);g.clear();assert.ok(enter(g,[3,'−',2]).ok);assert.equal(g.data.status,'playing');assert.ok(enter(g,[8,'÷',8]).ok);const r=g.declare('complete',12.4);assert.ok(r.ok);assert.equal(r.result.total,1076);assert.equal(g.data.cumulativeScore,'1076');});
test('A08 second tutorial example',()=>{const g=round(2);assert.ok(enter(g,[6,'÷',3]).ok);assert.ok(enter(g,[5,'−',3]).ok);assert.ok(g.declare('complete',12).ok);});
test('A09 impossible tutorial',()=>{const g=round(3);assert.equal(g.case.isImpossible,true);const r=g.declare('impossible',5);assert.equal(r.result.total,1200);});
test('A10 A11 A20 guarded declarations, zero floor, penalties, selected tiles still count',()=>{const g=round();assert.deepEqual(g.declare('complete',1),{ignored:true});g.select(0);assert.equal(g.declare('impossible',1).penalty,0);assert.equal(g.selected.length,0);g.data.cumulativeScore=130;assert.equal(g.declare('impossible',2).penalty,130);assert.equal(g.data.cumulativeScore,'0');assert.equal(g.data.round.accumulatedActualPenalty,'130');enter(g,[3,'−',2]);assert.deepEqual(g.declare('impossible',3),{ignored:true});assert.equal(g.declare('complete',3).ok,false);assert.ok(E.hasSolution(g.case,g.data.attempt.remainingMask));});
test('A12 long-only solution is included',()=>{const v=[2,3,4,'+','×'],r=E.solve(v,14);assert.ok(r.solutionMasks.includes(31));assert.ok(r.witnessExpressions.every(w=>w.length===5));});
test('A13 score examples and floor',()=>{assert.equal(E.reward(1,12.4,[{numbers:2},{numbers:2}],false).total,1076);assert.equal(E.reward(1,9999,[{numbers:5}],false).total,550);assert.equal(E.reward(1,5,[],true).total,1200);});
test('A14 A15 restart discards pending rewards, preserves paid penalties and type',()=>{let g=round();g.data.cumulativeScore=1000;g.declare('impossible',1);enter(g,[3,'−',2]);const old=g.case;g=new Game(cases,structuredClone(g.data));assert.equal(g.data.status,'ready');assert.equal(g.data.cumulativeScore,'800');assert.equal(g.data.round.accumulatedActualPenalty,'200');g.prepare();assert.notEqual(g.case.caseId,old.caseId);assert.equal(g.case.isImpossible,old.isImpossible);assert.equal(g.data.attempt.solvedExpressions.length,0);assert.equal(g.data.attempt.elapsedMs,0);});
test('A16 settlement is idempotent and result reload preserves next target',()=>{const g=round(3);g.declare('impossible',5);const score=g.data.cumulativeScore;assert.deepEqual(g.declare('impossible',5),{ignored:true});assert.equal(g.data.cumulativeScore,score);const restored=new Game(cases,structuredClone(g.data));assert.equal(restored.data.currentTarget,4);assert.equal(restored.data.status,'result');restored.next();assert.equal(restored.data.currentTarget,4);assert.equal(restored.data.cumulativeScore,score);});
test('A18 reject missing verification or incompatible content',()=>{for(const patch of [{rulesVersion:'old'},{contentHash:'bad'},{verification:null},{solutionMasks:null}])assert.equal(E.validCase({...cases[0],...patch}),false);});
test('A19 full 20-stage run, no repeat rewards',()=>{const g=new Game(cases);for(let t=1;t<=20;t++){g.prepare();g.start();let index;while((index=g.case.solutionMasks.findIndex(s=>(s&g.data.attempt.remainingMask)===s))>=0){for(const id of g.case.witnessExpressions[index])assert.ok(g.select(id));assert.ok(g.submit().ok);}assert.ok(g.declare(g.data.attempt.solvedExpressions.length?'complete':'impossible',5).ok);g.next();g.mini('skip');g.next();}assert.equal(g.data.status,'finished');assert.equal(g.data.history.length,20);const score=g.data.cumulativeScore;g.next();g.prepare();assert.equal(g.data.status,'finished');assert.equal(g.data.cumulativeScore,score);});
test('120 cases: exhaustive regeneration, every witness, masks, alternatives, tier sizes',()=>{assert.equal(cases.length,120);for(const c of cases){assert.ok(E.validCase(c));const regenerated=E.solve(c.values,c.target);assert.deepEqual(regenerated.solutionMasks,c.solutionMasks);assert.equal(regenerated.maxRemovableTiles,c.maxRemovableTiles);for(let i=0;i<c.solutionMasks.length;i++){const path=c.witnessExpressions[i];assert.equal(new Set(path).size,path.length);assert.equal(path.reduce((m,id)=>m|(1<<id),0),c.solutionMasks[i]);assert.ok(E.equal(E.evaluate(path.map(id=>c.values[id])),c.target));}assert.ok(cases.some(other=>other.caseId!==c.caseId&&other.target===c.target&&other.isImpossible===c.isImpossible&&other.difficultyBand===c.difficultyBand));}});
console.log(`${total} test suites passed`);

