(function(root){
  const format=n=>BigInt(n).toLocaleString('ko-KR');
  const signed=n=>`${BigInt(n)>0n?'+':BigInt(n)<0n?'−':''}${format(BigInt(n)<0n?-BigInt(n):n)}`;
  class Host{
    constructor({container,getData,command,next,notice}){Object.assign(this,{container,getData,command,next,notice});this.key=null;this.view=null;this.selected=0n;this.busy=false;this.pending=null;this.retry=null;}
    get opportunity(){return this.getData().pendingMiniGame;}
    show(){const o=this.opportunity,plugin=root.MiniGames.registry.get(o.type),key=`${o.miniGameId}:${o.status}`;
      if(this.key===key){this.updateBalance();return;}
      const sameActive=this.view&&this.key?.startsWith(o.miniGameId)&&['COUNTDOWN','RUNNING','MEMORIZE','RECALL','QUESTION','FEEDBACK'].includes(o.status);
      this.key=key;
      if(sameActive){this.view.update(o);return;}
      this.view?.dispose();this.view=null;
      if(o.status==='OFFERED'){this.selected=0n;this.renderOffer(plugin);}
      else if(['COUNTDOWN','RUNNING','MEMORIZE','RECALL','QUESTION','FEEDBACK'].includes(o.status)){
        const previousButton=this.q('#mini-start');const actionTop=previousButton?previousButton.getBoundingClientRect().top-this.container.getBoundingClientRect().top:null;
        this.container.innerHTML='<div class="mini-game"><div class="eyebrow">BONUS ROUND</div><div id="mini-runtime"></div></div>';
        this.view=plugin.mount({container:this.container.querySelector('#mini-runtime'),actionTop,actionContainer:this.container,opportunity:o,getBalance:()=>this.getData().cumulativeScore,command:(type,payload)=>this.send(type,payload),settle:payload=>this.settle(payload)});
        if(document.hidden)this.interrupt();
      }else this.renderResult(plugin);
    }
    async send(type,payload={}){const id=root.MiniGames.uid(),miniGameId=this.opportunity.miniGameId;return this.command(type,{...payload,miniGameId},id);}
    renderOffer(plugin){const o=this.opportunity,offer=plugin.offer(o);this.container.innerHTML=`<div class="mini-game"><div class="mini-badge">STAGE CLEAR · BONUS ROUND</div><h2>${plugin.title}</h2><p class="mini-copy">한 판을 마친 당신에게, 짧은 도전 하나.</p><div class="mini-target"><span>목표</span><strong>${offer.target}</strong><p>${offer.instruction}</p></div><div class="mini-wallet"><span>누적 보유 점수</span><b id="mini-balance"></b></div><div class="mini-bet"><div class="mini-bet-label">걸 점수 <span>100점 단위</span></div><div class="mini-counter"><button id="mini-minus" aria-label="베팅 100점 줄이기">−</button><strong id="mini-stake">0</strong><button id="mini-plus" aria-label="베팅 100점 늘리기">+</button></div><div id="mini-slider" role="slider" tabindex="0" aria-label="미니게임 베팅 점수" aria-valuemin="0"><i></i><b></b></div><div class="mini-maxrow"><span>0점</span><button id="mini-max"></button></div><div class="mini-after"><span>차감 후 잔액</span><b id="mini-after"></b></div></div><div class="mini-rewards">${offer.rewards.map(r=>`<span>${r}</span>`).join('')}</div><p class="mini-copy">배당은 원금 포함 · 1배는 원금 반환</p><p class="mini-warning">시작 후 앱을 나가면 베팅 점수를 잃어요.<br>준비 카운트다운 중에도 적용돼요.</p><button id="mini-start" class="primary" disabled>점수를 선택해 주세요</button><button id="mini-skip" class="mini-secondary">건너뛰고 ${this.getData().currentTarget>20?'전체 결과 보기':'다음 단계로'}</button></div>`;
      this.q('#mini-minus').onclick=()=>{if(!this.busy){this.selected-=100n;this.updateBalance();}};this.q('#mini-plus').onclick=()=>{if(!this.busy){this.selected+=100n;this.updateBalance();}};this.q('#mini-max').onclick=()=>{if(!this.busy){this.selected=BigInt(this.getData().cumulativeScore)/100n*100n;this.updateBalance();}};
      const slider=this.q('#mini-slider');let dragging=false;const slide=e=>{if(this.busy)return;const r=slider.getBoundingClientRect(),fraction=BigInt(Math.round(Math.max(0,Math.min(1,(e.clientX-r.left)/r.width))*1000000));this.selected=((BigInt(this.getData().cumulativeScore)/100n*fraction+500000n)/1000000n)*100n;this.updateBalance();};slider.onpointerdown=e=>{if(e.button!==0)return;dragging=true;slider.setPointerCapture(e.pointerId);slide(e);};slider.onpointermove=e=>{if(dragging)slide(e);};slider.onpointerup=slider.onpointercancel=()=>dragging=false;slider.onkeydown=e=>{if(this.busy)return;if(['ArrowLeft','ArrowDown'].includes(e.key))this.selected-=100n;else if(['ArrowRight','ArrowUp'].includes(e.key))this.selected+=100n;else if(e.key==='Home')this.selected=0n;else if(e.key==='End')this.selected=BigInt(this.getData().cumulativeScore)/100n*100n;else return;e.preventDefault();this.updateBalance();};
      this.q('#mini-start').onclick=async()=>{if(this.busy)return;this.busy=true;const stake=String(this.selected),expectedBalance=this.getData().cumulativeScore;this.updateBalance();try{await this.send('start',{stake,expectedBalance});}catch(e){this.notice(e.message,true);}finally{this.busy=false;this.updateBalance();}};
      this.q('#mini-skip').onclick=async()=>{if(this.busy)return;this.busy=true;this.updateBalance();try{await this.send('skip');await this.next();}catch(e){this.notice(e.message,true);}finally{this.busy=false;this.updateBalance();}};this.updateBalance();
    }
    q(selector){return this.container.querySelector(selector);}
    updateBalance(){if(this.opportunity?.status!=='OFFERED'||!this.q('#mini-stake'))return;const balance=BigInt(this.getData().cumulativeScore),max=balance/100n*100n;this.selected=this.selected<0n?0n:this.selected>max?max:this.selected;this.q('#mini-balance').textContent=`${format(balance)}점`;this.q('#mini-stake').textContent=format(this.selected);this.q('#mini-after').textContent=`${format(balance-this.selected)}점`;this.q('#mini-max').textContent=`최대 ${format(max)}점`;this.q('#mini-minus').disabled=this.busy||this.selected===0n;this.q('#mini-plus').disabled=this.busy||this.selected===max;this.q('#mini-max').disabled=this.busy||max===0n;const slider=this.q('#mini-slider'),ratio=max?Number(this.selected*10000n/max)/100:0;slider.style.setProperty('--fill',`${ratio}%`);slider.setAttribute('aria-valuemax',String(max));slider.setAttribute('aria-valuenow',String(this.selected));slider.setAttribute('aria-valuetext',`${format(this.selected)}점`);slider.setAttribute('aria-disabled',String(this.busy||max===0n));this.q('#mini-start').disabled=this.busy||this.selected<100n;this.q('#mini-start').textContent=max===0n?'베팅에는 100점 이상이 필요해요':this.selected?`${format(this.selected)}점 걸고 시작 →`:'점수를 선택해 주세요';this.q('#mini-skip').disabled=this.busy;}
    settle(payload){if(this.pending)return;this.pending={type:'settle',payload:{...payload,miniGameId:this.opportunity.miniGameId},eventId:root.MiniGames.uid()};this.saveSettlement();}
    async saveSettlement(){const fixed=this.pending;if(!fixed)return;try{await this.command(fixed.type,fixed.payload,fixed.eventId);if(this.pending===fixed)this.pending=null;}catch(e){this.notice('측정 결과를 고정하고 저장만 다시 시도하고 있어요.',true);this.retry=setTimeout(()=>this.saveSettlement(),1000);}}
    interrupt(){if(!this.opportunity||!['COUNTDOWN','RUNNING','MEMORIZE','RECALL','QUESTION','FEEDBACK'].includes(this.opportunity.status)||this.pending)return;const payload=this.view?.interruption?.()||{reason:'interrupted',elapsedMs:null};this.view?.dispose();this.view=null;this.settle(payload);}
    renderResult(plugin){const o=this.opportunity,skipped=o.status==='SKIPPED',r=o.result,view=skipped?{title:'이번 기회는 건너뛰었어요',record:'점수 변동 없음',detail:'다음 도전을 이어가세요.'}:plugin.result(o);this.container.innerHTML=`<div class="mini-game mini-result"><div class="result-mark">${skipped?'→':r.multiplier>=2?'✳':'·'}</div><div class="eyebrow">${plugin.title} · RESULT</div><h2>${view.title}</h2><div class="mini-record"><strong>${view.record}</strong><p>${view.detail}</p></div>${!skipped&&plugin.review?plugin.review(o):''}<div class="result-list"><div><span>베팅 점수</span><b>${format(o.bet?.stake||0)}점</b></div><div><span>지급액 ${r?`· 원금 포함 ×${r.multiplier}`:''}</span><b>${format(r?.payout||0)}점</b></div><div class="sum"><span>미니게임 순증감</span><b>${signed(r?.netChange||0)}점</b></div><div><span>누적 보유 점수</span><b>${format(this.getData().cumulativeScore)}점</b></div></div><button id="mini-next" class="primary">${this.getData().currentTarget>20?'전체 결과 보기':'다음 단계로'} →</button><p class="mini-copy">이번 기회는 끝났어요. 다음 스테이지에도 새로운 도전이 기다려요.</p></div>`;this.q('#mini-next').onclick=()=>this.next();}
    dispose(){this.view?.dispose();this.view=null;clearTimeout(this.retry);this.retry=null;this.key=null;}
  }
  root.MiniGameHost=Host;
})(globalThis);
