'use strict';
const E=TimerEngine,$=id=>document.getElementById(id),points=value=>BigInt(value).toLocaleString('ko-KR'),seconds=ms=>(Math.floor(ms)/1000).toFixed(3);
const isQA=new URLSearchParams(location.search).has('test');
const dbName=isQA?'chagok-timer-stop-qa-v1':'chagok-timer-stop-v1';
const store=new TimerStore(dbName);
let data=null,selected=0n,busy=true,owner=false,blocked=false,starting=false,interruptionRequested=false;
let session=null,live=false,pendingSettlement=null,frame=0,countTimer=0,deadlineTimer=0,drainTimer=0,retryTimer=0,toastTimer=0;
let releaseOwnership,suppressStopClick=false;
const command=(type,extra={})=>({type,eventId:E.uid(),miniGameId:data?.opportunity.miniGameId,...extra});
function toast(message){$('notice').textContent=message;$('notice').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('notice').hidden=true,4800);}
function setPanel(name){for(const id of ['offer','running','result','blocked'])$(`${id}-panel`).hidden=id!==name;}
function setAction(label,enabled=true){$('main-action').textContent=label;$('main-action').disabled=!enabled;}
function signed(value){const n=BigInt(value);return `${n>0n?'+':n<0n?'−':''}${points(n<0n?-n:n)}점`;}
function stopTimers(){cancelAnimationFrame(frame);clearTimeout(countTimer);clearTimeout(deadlineTimer);clearTimeout(drainTimer);live=false;}
function syncHeader(){if(!data)return;const o=data.opportunity;$('target').textContent=seconds(o.targetMs);$('round-label').textContent=`TEST ${String(data.testRound).padStart(2,'0')}`;document.body.classList.toggle('large-points',data.balance.length>12);renderHistory();renderRules();}
function renderRules(){const c=data.opportunity.config,tiers=[[c.exactMaxMs,c.multipliers.exact,'exact'],[c.doubleMaxMs,c.multipliers.double,'double'],[c.refundMaxMs,c.multipliers.refund,'refund']];document.querySelector('.payout-strip').innerHTML=tiers.map(([ms,m])=>`<div><b>${m}<span>배</span></b><small>±${seconds(ms)}초</small></div>`).join('');document.querySelectorAll('.reward-row').forEach((row,i)=>{if(i<3){const [ms,m,cls]=tiers[i];row.innerHTML=`<span><i class="swatch ${cls}"></i>±${seconds(ms)}초 이내</span><b>×${m}</b>`;}});document.querySelector('.tip p').innerHTML=`500점을 걸고 ${c.multipliers.exact}배에 성공하면<br><b>${points(500*c.multipliers.exact)}점 지급, 순증감 +${points(500*(c.multipliers.exact-1))}점.</b>`;}
function renderHistory(){const list=data.history.slice(-4).reverse();$('history-count').textContent=`${data.history.length}회`;$('history').innerHTML=list.length?list.map(o=>`<div class="history-row"><span>${seconds(o.targetMs)}초</span><small>${o.status==='SKIPPED'?'건너뜀':o.result.endReason==='interrupted'?'중단':o.result.endReason==='timeout'?'시간 초과':`×${o.result.multiplier}`}</small><b>${o.result?signed(o.result.netChange):'—'}</b></div>`).join(''):'<div class="empty-history">아직 기록이 없어요.<br>첫 번째 순간을 남겨보세요.</div>';}
function render(){if(!data||blocked)return;syncHeader();const o=data.opportunity;document.body.classList.toggle('is-playing',['COUNTDOWN','RUNNING'].includes(o.status));$('help').disabled=['COUNTDOWN','RUNNING'].includes(o.status);$('lab').disabled=['COUNTDOWN','RUNNING'].includes(o.status);$('main-action').classList.remove('stop');$('secondary-action').hidden=false;$('warning').style.visibility='visible';
  if(o.status==='OFFERED')renderOffer();else if(o.status==='SETTLED'||o.status==='SKIPPED')renderResult();else renderActive();
}
function renderOffer(){setPanel('offer');$('phase-label').textContent='베팅 준비';$('phase-dots').textContent='● ─ ○ ─ ○';$('target-label').textContent='목표 시간';$('target-copy').textContent='목표 시간에 최대한 가깝게 멈추세요';$('warning').innerHTML='시작 후 앱을 나가면 베팅 점수를 잃어요.<br><span>준비 카운트다운 중에도 적용돼요.</span>';$('secondary-action').textContent=BigInt(data.balance)<100n?'다음 테스트로':'이번 테스트 건너뛰기';updateStake();}
function updateStake(){if(!data||data.opportunity.status!=='OFFERED')return;const max=E.maxStake(data.balance,data.opportunity.config);if(selected>max)selected=max;if(selected<0n)selected=0n;$('balance').textContent=`${points(data.balance)}점`;$('stake').textContent=points(selected);$('after-balance').textContent=`${points(BigInt(data.balance)-selected)}점`;$('max-value').textContent=points(max);$('minus').disabled=busy||selected===0n;$('plus').disabled=busy||selected>=max;$('max').disabled=busy||max===0n;
  const ratio=max?Number(selected*100000n/max)/1000:0;$('slider-fill').style.width=`${ratio}%`;$('slider-thumb').style.left=`${ratio}%`;
  $('stake-slider').setAttribute('aria-valuemax',String(max));$('stake-slider').setAttribute('aria-valuenow',String(selected));$('stake-slider').setAttribute('aria-valuetext',`${points(selected)}점`);$('stake-slider').setAttribute('aria-disabled',String(busy||max===0n));
  if(max===0n){setAction('베팅에는 100점 이상이 필요해요',false);}else setAction(selected?`${points(selected)}점 걸고 시작 →`:'점수를 선택해 주세요 →',!busy&&selected>=100n);
}
function renderActive(){setPanel('running');const o=data.opportunity,isCountdown=o.status==='COUNTDOWN';$('phase-label').textContent=isCountdown?'준비 카운트다운':'타이밍 도전';$('phase-dots').textContent='○ ─ ● ─ ○';$('running-stake').textContent=`${points(o.bet.stake)}점`;$('running-balance').textContent=`${points(data.balance)}점`;$('target-copy').textContent='목표는 그대로, 내 감각에 집중하세요';$('warning').style.visibility='hidden';$('secondary-action').style.visibility='hidden';$('clock-caption').textContent=isCountdown?'준비':'경과 시간';$('clock-unit').textContent=isCountdown?'잠시 후 시작해요':'초';$('clock').classList.toggle('countdown',isCountdown);$('running-hint').textContent=isCountdown?'3, 2, 1이 끝나면 정지 버튼이 열려요.':'버튼에 닿는 순간, 시간이 멈춰요.';
  if(isCountdown){$('clock').textContent='3';$('clock-ring').style.setProperty('--sweep','0deg');setAction('준비 중',false);}else{$('main-action').classList.add('stop');setAction('■  지금 정지',live&&!pendingSettlement);}
}
function renderResult(){setPanel('result');const o=data.opportunity,skipped=o.status==='SKIPPED',r=o.result;$('phase-label').textContent=skipped?'건너뛰기 완료':'결과 저장 완료';$('phase-dots').textContent='○ ─ ○ ─ ●';$('target-copy').textContent=skipped?'이번 기회는 사용하지 않았어요':'이번 순간의 기록을 확인해 보세요';$('secondary-action').style.visibility='visible';$('secondary-action').textContent='테스트 기록 보기';$('warning').innerHTML='본게임과 분리된 테스트 점수로 플레이해요.<br><span>다음 테스트는 새로운 기회와 무작위 목표로 시작해요.</span>';
  if(skipped){$('result-title').textContent='다음 순간을 기다려요';$('result-symbol').textContent='→';$('result-description').textContent='점수 차감 없이 건너뛰었어요.';$('result-time').textContent='기록 없음';$('result-error').textContent='—';$('result-stake').textContent='0점';$('result-multiplier').textContent='';$('result-payout').textContent='0점';$('result-net').textContent='0점';$('result-net').classList.remove('negative');}
  else{const labels={5:'정확!',3:'정확!',2:'성공!',1:'원금 반환',0:'아쉬워요'};const ended=r.endReason!=='stopped';$('result-title').textContent=r.endReason==='interrupted'?'중단 종료':r.endReason==='timeout'?'시간 초과':labels[r.multiplier];$('result-symbol').textContent=r.multiplier>=2?'✳':r.multiplier===1?'↔':'·';$('result-description').textContent=r.endReason==='interrupted'?'화면을 벗어나 이번 베팅이 종료됐어요.':r.endReason==='timeout'?'정지하지 않아 이번 베팅이 종료됐어요.':r.multiplier===o.config.multipliers.exact?'감각이 딱 맞아떨어진 순간이에요.':r.multiplier===2?'목표 가까이, 잘 멈췄어요.':r.multiplier===1?'걸었던 점수를 그대로 돌려받아요.':'이번엔 목표와 조금 멀었어요.';
    $('result-time').textContent=ended?'정지 기록 없음':`${seconds(r.elapsedMs)}초`;$('result-error').textContent=ended?'—':`${seconds(r.absoluteErrorMs)}초${r.signedErrorMs<0?' 빠름':r.signedErrorMs>0?' 늦음':' · 일치'}`;$('result-stake').textContent=`${points(o.bet.stake)}점`;$('result-multiplier').textContent=`원금 포함 ×${r.multiplier}`;$('result-payout').textContent=`${points(r.payout)}점`;$('result-net').textContent=signed(r.netChange);$('result-net').classList.toggle('negative',BigInt(r.netChange)<0n);
  }
  $('result-balance').textContent=`${points(data.balance)}점`;setAction('다음 테스트 →',!busy);
}
async function perform(type,extra={}){if(busy||!owner)return false;busy=true;render();try{data=await store.command(command(type,extra));return true;}catch(e){toast(e.message);const current=await store.read().catch(()=>null);if(current)data=current;return false;}finally{busy=false;render();}}
async function start(){if(busy||!owner||!data||data.opportunity.status!=='OFFERED')return;const stake=String(selected),expectedBalance=data.balance;if(!E.validStake(stake,expectedBalance,data.opportunity.config))return;busy=true;starting=true;interruptionRequested=false;updateStake();
  try{data=await store.command(command('start',{stake,expectedBalance}));busy=false;starting=false;render();if(interruptionRequested||document.hidden){interrupt();return;}countdown();}
  catch(e){busy=false;starting=false;data=await store.read().catch(()=>data);selected=0n;render();toast(`시작하지 않았어요. ${e.message}`);}
}
function countdown(){const end=performance.now()+data.opportunity.config.countdownMs;function update(){if(data.opportunity.status!=='COUNTDOWN'||pendingSettlement)return;const remaining=end-performance.now();if(remaining<=0){startClock();return;}$('clock').textContent=String(Math.ceil(remaining/1000));countTimer=setTimeout(update,Math.min(100,remaining));}update();}
async function startClock(){if(pendingSettlement||data.opportunity.status!=='COUNTDOWN')return;busy=true;try{const current=await store.command(command('running'));data=current;if(pendingSettlement||document.hidden){busy=false;interrupt();return;}session=new E.TimerSession(performance.now(),data.opportunity.targetMs,data.opportunity.config);live=true;busy=false;render();$('clock').textContent='0.000';tick();scheduleDeadline();}catch(e){busy=false;toast('시작 상태를 저장하지 못해 이번 베팅을 중단 처리합니다.');interrupt();}}
function tick(){if(!live||!session)return;const elapsed=session.elapsed(performance.now()),limit=session.targetMs+session.config.refundMaxMs+1;$('clock').textContent=seconds(Math.min(elapsed,limit));$('clock-ring').style.setProperty('--sweep',`${Math.min(1,elapsed/session.targetMs)*360}deg`);frame=requestAnimationFrame(tick);}
function scheduleDeadline(){clearTimeout(deadlineTimer);if(!live||!session)return;const wait=session.targetMs+session.config.refundMaxMs+1-session.elapsed(performance.now());deadlineTimer=setTimeout(()=>{if(!live||!session||pendingSettlement)return;if(!session.deadline(performance.now())){scheduleDeadline();return;}
    cancelAnimationFrame(frame);$('clock').textContent=seconds(session.targetMs+session.config.refundMaxMs+1);$('clock-caption').textContent='CHECKING INPUT';$('running-hint').textContent='마감 전에 도착한 입력을 확인하고 있어요.';
    // Drain an already queued input before committing timeout. This never extends the
    // valid timestamp interval: timestamps at/after target+201ms always lose.
    drainTimer=setTimeout(()=>{if(pendingSettlement)return;const result=session.finishTimeout();if(result)settle(result);},session.config.inputDrainMs);
  },Math.max(0,wait));}
function stop(event){if(!owner||!live||!session||pendingSettlement||data.opportunity.status!=='RUNNING')return;const timestamp=E.normalizeTimestamp(event.timeStamp,performance.now(),performance.timeOrigin);const result=session.stop(timestamp);if(result)settle(result);}
function settle(result){if(pendingSettlement)return;stopTimers();busy=true;pendingSettlement=command('settle',{reason:result.endReason,elapsedMs:result.elapsedMs});$('clock').textContent=result.elapsedMs===null?'—.———':seconds(result.elapsedMs);$('clock-caption').textContent='SAVING RESULT';$('running-hint').textContent='기록을 저장하고 있어요.';setAction('정지 완료 · 저장 중',false);saveResult();}
async function saveResult(){if(!pendingSettlement)return;const fixed=pendingSettlement;try{data=await store.command(fixed);if(pendingSettlement!==fixed)return;pendingSettlement=null;busy=false;session=null;$('save-label').innerHTML='<i class="dot"></i> 로컬 자동 저장';render();}catch(e){$('save-label').textContent='결과 저장 재시도 중';$('running-hint').textContent='기록은 고정됐어요. 저장만 다시 시도하고 있어요.';clearTimeout(retryTimer);retryTimer=setTimeout(saveResult,1000);}}
function interrupt(){interruptionRequested=true;if(!owner||pendingSettlement||!data)return;if(['COUNTDOWN','RUNNING'].includes(data.opportunity.status))settle(E.judge(null,data.opportunity.targetMs,data.opportunity.config,'interrupted'));}
async function next(){if(await perform('next',{targetMs:E.target()})){selected=0n;session=null;interruptionRequested=false;$('secondary-action').style.visibility='visible';render();}}
$('main-action').addEventListener('pointerdown',event=>{if(event.button!==0)return;suppressStopClick=false;if(live){suppressStopClick=true;event.preventDefault();stop(event);}});
$('main-action').addEventListener('click',event=>{if(suppressStopClick){suppressStopClick=false;return;}if(blocked){location.reload();return;}if(live){if(event.detail===0)stop(event);return;}if(busy||!data)return;if(data.opportunity.status==='OFFERED')start();else if(['SETTLED','SKIPPED'].includes(data.opportunity.status))next();});
$('main-action').addEventListener('contextmenu',event=>event.preventDefault());
document.addEventListener('keydown',event=>{if(event.repeat||$('dialog').open||!live||!['Space','Enter'].includes(event.code))return;event.preventDefault();stop(event);});
$('secondary-action').onclick=async()=>{if(!data||busy)return;if(data.opportunity.status==='OFFERED'){if(await perform('skip'))toast('점수 차감 없이 건너뛰었어요.');}else showLab();};
$('minus').onclick=()=>{if(!busy){selected=selected>=100n?selected-100n:0n;updateStake();}};$('plus').onclick=()=>{if(!busy){selected+=100n;updateStake();}};$('max').onclick=()=>{if(!busy){selected=E.maxStake(data.balance);updateStake();}};
let dragging=false;
function slide(event){if(busy||!owner||data?.opportunity.status!=='OFFERED')return;const box=$('stake-slider').getBoundingClientRect(),unit=Math.round(Math.max(0,Math.min(1,(event.clientX-box.left)/box.width))*1000000),steps=E.maxStake(data.balance)/100n;selected=((steps*BigInt(unit)+500000n)/1000000n)*100n;updateStake();}
$('stake-slider').onpointerdown=event=>{if(event.button!==0||busy)return;dragging=true;event.currentTarget.setPointerCapture(event.pointerId);slide(event);};$('stake-slider').onpointermove=event=>{if(dragging)slide(event);};$('stake-slider').onpointerup=$('stake-slider').onpointercancel=()=>{dragging=false;};
$('stake-slider').onkeydown=event=>{if(busy||data?.opportunity.status!=='OFFERED')return;if(['ArrowLeft','ArrowDown'].includes(event.key))selected-=100n;else if(['ArrowRight','ArrowUp'].includes(event.key))selected+=100n;else if(event.key==='Home')selected=0n;else if(event.key==='End')selected=E.maxStake(data.balance);else return;event.preventDefault();updateStake();};
function dialog(html){$('dialog-content').innerHTML=html;$('dialog').showModal();}
$('close-dialog').onclick=()=>$('dialog').close();
$('help').onclick=()=>{if(busy||!data)return;const c=data.opportunity.config;dialog(`<div class="eyebrow">ONE TOUCH, ONE MOMENT</div><h2>목표 시간에, 딱.</h2><ul><li>1~6초 중 무작위로 정해진 목표를 확인해요.</li><li>100점 단위로 점수를 선택해요. 시작할 때 즉시 차감돼요.</li><li>3, 2, 1이 끝나면 타이머가 움직여요. 버튼에 <b>닿는 순간</b> 정지해요. 키보드는 Space 또는 Enter.</li><li>오차 ±${seconds(c.exactMaxMs)}초까지 ${c.multipliers.exact}배, ±${seconds(c.doubleMaxMs)}초까지 ${c.multipliers.double}배, ±${seconds(c.refundMaxMs)}초까지 원금 반환이에요.</li><li>목표보다 ${seconds(c.refundMaxMs+1)}초 늦도록 정지하지 않으면 0배 종료돼요.</li><li>시작 후 화면을 벗어나거나 새로고침하면 베팅 점수를 잃어요. 카운트다운도 포함돼요.</li></ul><p>화면에는 일부 밀리초만 보이지만, 판정은 입력이 발생한 시간으로 계산해요. 이 버전의 점수는 본게임과 분리된 테스트 점수예요.</p>`);};
function exportData(){const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),prototype:'timer_stop',progress:data},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='chagok-timer-stop-playtest.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function showLab(){if(!data||busy||!owner)return;const settled=data.history.filter(x=>x.status==='SETTLED'),staked=settled.reduce((s,x)=>s+BigInt(x.bet.stake),0n),paid=settled.reduce((s,x)=>s+BigInt(x.result.payout),0n),rate=staked?`${Number(paid*10000n/staked)/100}%`:'—';
  dialog(`<div class="eyebrow">INDEPENDENT PLAYTEST</div><h2>테스트 도구</h2><p>본게임의 점수와 진행에는 영향이 없어요.<br>다음 테스트마다 새로운 기회를 만들며 잔액은 이어져요.</p><div class="metrics">완료 ${settled.length}회 · 건너뜀 ${data.history.filter(x=>x.status==='SKIPPED').length}회<br>3배 ${settled.filter(x=>x.result.multiplier===3).length} · 2배 ${settled.filter(x=>x.result.multiplier===2).length} · 1배 ${settled.filter(x=>x.result.multiplier===1).length} · 0배 ${settled.filter(x=>x.result.multiplier===0).length}<br>총지급 / 총베팅: ${rate}<br>중단 손실 ${settled.filter(x=>x.result.endReason==='interrupted').length}회</div><button class="tool-button" id="export">플레이 기록 JSON 내보내기</button><button class="tool-button" id="fund" ${data.opportunity.status==='OFFERED'?'':'disabled'}>테스트 점수 1,076점 추가</button><p>점수 추가는 준비 화면에서만 가능해요.<br>목표 시간과 이미 끝난 기회는 바뀌지 않아요.</p>`);$('export').onclick=exportData;$('fund').onclick=async()=>{$('dialog').close();if(await perform('fund'))toast('테스트 점수 1,076점을 추가했어요.');};
}
$('lab').onclick=showLab;
document.addEventListener('visibilitychange',()=>{if(document.hidden)interrupt();});window.addEventListener('pagehide',interrupt);
function renderBlocked(message){blocked=true;busy=true;setPanel('blocked');$('phase-label').textContent='연결 대기';$('target').textContent='—.———';$('target-copy').textContent='한 번에 한 탭에서 테스트해요';$('warning').style.visibility='hidden';$('secondary-action').hidden=true;$('lab').disabled=true;$('help').disabled=true;setAction('다시 연결',true);$('save-label').textContent=message||'다른 탭에서 사용 중';}
async function init(){try{await store.open();if(!navigator.locks){renderBlocked('이 브라우저는 탭 잠금을 지원하지 않아요.');return;}
    navigator.locks.request(`${dbName}-owner`,{mode:'exclusive',ifAvailable:true},async lock=>{if(!lock){renderBlocked();return;}owner=true;try{data=await store.initialize();if(data.schemaVersion!==1)throw Error('저장 버전이 맞지 않아요.');if(['COUNTDOWN','RUNNING'].includes(data.opportunity.status)){data=await store.command(command('settle',{reason:'interrupted',elapsedMs:null}));}busy=false;render();}catch(e){renderBlocked(`저장 공간 오류: ${e.message}`);}await new Promise(resolve=>{releaseOwnership=resolve;});}).catch(e=>renderBlocked(e.message));
  }catch(e){renderBlocked('저장 공간을 열지 못했어요. 일반 브라우저 창에서 다시 열어 주세요.');}}
init();

