(async()=>{
  const E=TimerEngine,store=new TimerStore(`timer-stop-tests-${E.uid()}`),out=document.getElementById('results');let passed=0,failed=0;
  const assert=(condition,message)=>{if(!condition)throw Error(message);};
  const cmd=(type,d,extra={})=>({type,eventId:E.uid(),miniGameId:d.opportunity.miniGameId,...extra});
  async function test(name,fn){const li=document.createElement('li');try{await fn();li.textContent=`PASS ${name}`;passed++;}catch(e){li.textContent=`FAIL ${name}: ${e.message}`;li.className='fail';failed++;}out.append(li);}
  await store.open();
  await test('T19 concurrent start transactions deduct only once',async()=>{await store.update(()=>E.fresh(6000));const d=await store.read(),a=cmd('start',d,{stake:'500',expectedBalance:'1076'}),b=cmd('start',d,{stake:'500',expectedBalance:'1076'});const results=await Promise.allSettled([store.command(a),store.command(b)]);assert(results.filter(x=>x.status==='fulfilled').length===1,'두 번 시작됨');assert((await store.read()).balance==='576','중복 차감');});
  await test('T21 write failure aborts debit and state change atomically',async()=>{await store.update(()=>E.fresh(6000));const before=await store.read();let rejected=false;try{await store.update(d=>{const next=E.apply(d,cmd('start',d,{stake:'500',expectedBalance:'1076'}));next.nonCloneable=()=>{};return next;});}catch{rejected=true;}const after=await store.read();assert(rejected,'실패를 감지하지 못함');assert(after.balance===before.balance&&after.opportunity.status==='OFFERED','차감 또는 상태 누출');});
  await test('T15 concurrent settlement pays once; repeating identical event is harmless',async()=>{let d=await store.read();d=await store.command(cmd('start',d,{stake:'500',expectedBalance:d.balance}));d=await store.command(cmd('running',d));const c=cmd('settle',d,{reason:'stopped',elapsedMs:6000});await Promise.all([store.command(c),store.command({...c,eventId:E.uid()})]);await store.command(c);const after=await store.read();assert(after.balance==='2076','중복 지급');assert(after.history.length===1,'중복 기록');});
  await test('stop save failure leaves debit durable; same result event retries successfully',async()=>{await store.update(()=>E.fresh(6000));let d=await store.read();d=await store.command(cmd('start',d,{stake:'500',expectedBalance:d.balance}));d=await store.command(cmd('running',d));const c=cmd('settle',d,{reason:'stopped',elapsedMs:6050});try{await store.update(v=>{const next=E.apply(v,c);next.bad=()=>{};return next;});}catch{}assert((await store.read()).balance==='576','실패한 지급이 반영됨');await store.command(c);await store.command(c);assert((await store.read()).balance==='2076','재시도 결과 오류');});
  await test('T14 new store instance recovers unfinished countdown without extra debit',async()=>{await store.update(()=>E.fresh(6000));let d=await store.read();await store.command(cmd('start',d,{stake:'500',expectedBalance:d.balance}));const reopened=new TimerStore(store.name);await reopened.open();d=await reopened.read();d=await reopened.command(cmd('settle',d,{reason:'interrupted',elapsedMs:null}));assert(d.balance==='576'&&d.opportunity.result.elapsedMs===null,'중단 복구 오류');reopened.db.close();});
  await test('exclusive browser lock blocks a second owner',async()=>{const lockName=`timer-stop-test-lock-${E.uid()}`;let unlock;const hold=navigator.locks.request(lockName,async()=>{await new Promise(resolve=>{unlock=resolve;});});while(!unlock)await new Promise(resolve=>setTimeout(resolve,1));try{const acquired=await navigator.locks.request(lockName,{ifAvailable:true},lock=>Boolean(lock));assert(acquired===false,'중복 소유권');}finally{unlock();await hold;}});
  document.getElementById('summary').textContent=`${passed} passed · ${failed} failed`;store.db.close();indexedDB.deleteDatabase(store.name);
})();


