const assert=require('node:assert/strict'),E=require('./engine.js');
let count=0;
function test(name,fn){fn();count++;console.log('PASS',name);}
const cmd=(type,d,extra={})=>({type,eventId:E.uid(),miniGameId:d.opportunity.miniGameId,...extra});
function start(balance='1076',target=6000,stake='500'){let d=E.fresh(target);d.balance=balance;d=E.apply(d,cmd('start',d,{stake,expectedBalance:balance}));return d;}
function running(balance,target,stake){let d=start(balance,target,stake);return E.apply(d,cmd('running',d));}
test('T03 T04 T05 100-point stake validation, max and remainder',()=>{assert.equal(E.maxStake('1076'),1000n);assert.equal(E.maxStake('99'),0n);for(const b of ['0','150','1100','-100','100.5'])assert.equal(E.validStake(b,'1076'),false);assert.equal(E.validStake('1000','1076'),true);assert.equal(start('1076',6000,'1000').balance,'76');for(const b of ['0','150','1100']){const d=E.fresh(6000);assert.throws(()=>E.apply(d,cmd('start',d,{stake:b,expectedBalance:'1076'})));assert.equal(d.balance,'1076');}});
test('T06 T07 T08 T09 all symmetric v2 payout boundaries',()=>{for(const [error,m] of [[0,3],[49,3],[50,3],[51,2],[99,2],[100,2],[101,1],[199,1],[200,1],[201,0],[2000,0]])for(const sign of [-1,1]){const r=E.judge(6000+error*sign,6000);assert.equal(r.multiplier,m,`${error*sign}ms`);assert.equal(r.absoluteErrorMs,error);}});
test('integer floor is applied before payout and display',()=>{assert.equal(E.judge(6050.999,6000).multiplier,3);assert.equal(E.judge(6051,6000).multiplier,2);assert.equal(E.judge(5949.999,6000).elapsedMs,5949);assert.equal(E.judge(5949.999,6000).multiplier,2);});
test('T10 T11 principal-inclusive payout and net',()=>{for(const [time,balance,net] of [[6000,'2076','1000'],[6150,'1076','0'],[5000,'576','-500']]){let d=running();d=E.apply(d,cmd('settle',d,{reason:'stopped',elapsedMs:time}));assert.equal(d.balance,balance);assert.equal(d.opportunity.result.netChange,net);assert.equal(d.opportunity.result.payout,String(BigInt(net)+500n));}});
test('T12 target 10 seconds allows late valid stop',()=>{const timer=new E.TimerSession(400,10000);assert.equal(timer.deadline(10400),false);assert.equal(timer.stop(10500).multiplier,2);const t2=new E.TimerSession(400,10000);assert.equal(t2.stop(10600).multiplier,1);});
test('T13 offered state keeps target with no charge and frozen config',()=>{const d=E.fresh(7000),restored=JSON.parse(JSON.stringify(d));assert.equal(restored.opportunity.targetMs,7000);assert.equal(restored.balance,'1076');const config=structuredClone(E.CONFIG);const o=E.opportunity('round',6000,config);config.exactMaxMs=200;assert.equal(o.config.exactMaxMs,50);});
test('T14 countdown and running interruption settle once without extra charge',()=>{for(const d of [start(),running()]){const result=E.apply(d,cmd('settle',d,{reason:'interrupted',elapsedMs:null}));assert.equal(result.balance,'576');assert.equal(result.opportunity.result.multiplier,0);assert.equal(result.opportunity.result.elapsedMs,null);assert.equal(result.opportunity.result.payout,'0');assert.throws(()=>E.apply(result,cmd('start',result,{stake:'100',expectedBalance:result.balance})));assert.equal(E.apply(result,cmd('settle',result,{reason:'interrupted',elapsedMs:null})).balance,'576');}});
test('T15 duplicate event and different-event duplicate settlement cannot pay twice',()=>{let d=running();const c=cmd('settle',d,{reason:'stopped',elapsedMs:6000});d=E.apply(d,c);const repeated=E.apply(d,c);assert.deepEqual(repeated,d);assert.equal(E.apply(d,cmd('settle',d,{reason:'stopped',elapsedMs:6000})).balance,'2076');assert.equal(d.history.length,1);});
test('T16 T17 input before start ignored and first contact wins',()=>{const timer=new E.TimerSession(1000,6000);assert.equal(timer.stop(999),null);assert.equal(timer.result,null);assert.equal(timer.stop(7050).multiplier,3);assert.equal(timer.stop(7300),null);assert.equal(timer.result.elapsedMs,6050);const d=start();assert.throws(()=>E.apply(d,cmd('settle',d,{reason:'stopped',elapsedMs:6000})));});
test('T18 frame-independent fake clock, normalized event timestamps',()=>{const timer=new E.TimerSession(1000,6000);assert.equal(timer.elapsed(6347),5347);const origin=1700000000000;assert.equal(E.normalizeTimestamp(origin+7050,7500,origin),7050);assert.equal(E.normalizeTimestamp(7050,7500,origin),7050);assert.equal(timer.stop(E.normalizeTimestamp(7050,7500,origin)).multiplier,3);assert.equal(E.normalizeTimestamp(0,7100,origin),7100);});
test('deadline callback then delayed pre-deadline input uses event time',()=>{const timer=new E.TimerSession(1000,6000);assert.equal(timer.deadline(7201),true);assert.equal(timer.stop(7100).multiplier,2);assert.equal(timer.finishTimeout().multiplier,2);});
test('late stop and no-stop timeout never succeed, no fabricated record',()=>{const timer=new E.TimerSession(1000,6000);assert.equal(timer.stop(7201).endReason,'timeout');assert.equal(timer.result.elapsedMs,null);const t2=new E.TimerSession(1000,6000);assert.equal(t2.deadline(7200),false);assert.equal(t2.deadline(7201),true);assert.equal(t2.finishTimeout().multiplier,0);assert.equal(t2.stop(7199),null);});
test('T19 stale balance and repeated opportunity start rejected',()=>{const d=E.fresh(6000);assert.throws(()=>E.apply(d,cmd('start',d,{stake:'100',expectedBalance:'1000'})));const a=E.apply(d,cmd('start',d,{stake:'500',expectedBalance:'1076'}));assert.throws(()=>E.apply(a,cmd('start',a,{stake:'500',expectedBalance:'1076'})));assert.equal(a.balance,'576');});
test('skip consumes opportunity, test next makes a distinct chance without bonus points',()=>{let d=E.fresh(6000);const id=d.opportunity.miniGameId;d=E.apply(d,cmd('skip',d));assert.equal(d.balance,'1076');assert.throws(()=>E.apply(d,cmd('start',d,{stake:'100',expectedBalance:'1076'})));d=E.apply(d,cmd('next',d,{targetMs:10000}));assert.notEqual(d.opportunity.miniGameId,id);assert.equal(d.opportunity.targetMs,10000);assert.equal(d.balance,'1076');assert.equal(d.testRound,2);});
test('T22 very large balances stay exact through debit, 3x, and JSON roundtrip',()=>{const balance='900719925474099312345678976',stake=E.maxStake(balance).toString();let d=running(balance,6000,stake);d=E.apply(d,cmd('settle',d,{reason:'stopped',elapsedMs:6000}));const expected=BigInt(balance)+BigInt(stake)*2n;assert.equal(d.balance,String(expected));assert.equal(JSON.parse(JSON.stringify(d)).balance,String(expected));assert.throws(()=>E.amount(Number.MAX_SAFE_INTEGER+1));});
test('v2 upgrades only unused offers; target and balance remain, started bets keep agreed rules',()=>{let d=E.fresh(6000);d.opportunity.rulesVersion='timer-stop-v1';d.opportunity.config.rulesVersion='timer-stop-v1';d.opportunity.config.multipliers.exact=5;d.opportunity.config.doubleMaxMs=200;d.opportunity.config.refundMaxMs=300;const upgraded=E.upgradeOffered(d);assert.equal(upgraded.opportunity.config.multipliers.exact,3);assert.equal(upgraded.opportunity.targetMs,6000);assert.equal(upgraded.balance,d.balance);d=E.apply(d,cmd('start',d,{stake:'500',expectedBalance:d.balance}));assert.equal(E.upgradeOffered(d).opportunity.config.multipliers.exact,5);});
test('all ten targets including 10s selectable and rejection sampling unbiased',()=>{for(let i=0;i<10;i++)assert.equal(E.target(()=>i),(i+1)*1000);const samples=[4294967295,9];assert.equal(E.target(()=>samples.shift()),10000);});
console.log(`${count} test suites passed`);
