'use strict';
let store,game,host,busy=false,owner=false;
const $=id=>document.getElementById(id),notice=message=>$('notice').textContent=message;
function offer(g){const p=MiniGames.registry.get('dice_roll'),c=p.create();g.data.status='minigame';g.data.currentTarget=1;g.data.pendingMiniGame={...c,type:p.type,title:p.title,miniGameId:MiniGames.uid(),sourceRoundId:MiniGames.uid(),status:'OFFERED',bet:null,result:null};g.data.pendingMiniGameId=g.data.pendingMiniGame.miniGameId;}
function render(){document.body.classList.toggle('dice-active',['COUNTDOWN','RUNNING'].includes(game.data.pendingMiniGame.status));$('lab-balance').textContent=BigInt(game.data.cumulativeScore).toLocaleString();$('reset-lab').disabled=['COUNTDOWN','RUNNING'].includes(game.data.pendingMiniGame.status);host.show();const next=$('mini-next'),skip=$('mini-skip');if(next)next.textContent='새로운 주사위 도전 →';if(skip)skip.textContent='이번 테스트 건너뛰기';}
async function commit(fn){if(!owner)throw Error('다른 탭에서 진행 중이에요.');const saved=await store.update(fn);game=saved.model;render();return saved;}
async function connect(){owner=true;let saved=await store.update(g=>{if(!g.data.pendingMiniGame){g.data.cumulativeScore='3000';offer(g);}else if(['COUNTDOWN','RUNNING'].includes(g.data.pendingMiniGame.status))g.mini('settle',{reason:'interrupted',elapsedMs:null});});game=saved.model;host=new MiniGameHost({container:$('screen'),getData:()=>game.data,command:(type,payload,id)=>commit(g=>g.mini(type,payload,id)),next:()=>commit(g=>offer(g)),notice});render();}
$('reset-lab').onclick=async()=>{if(busy||['COUNTDOWN','RUNNING'].includes(game.data.pendingMiniGame.status))return;busy=true;try{await commit(g=>{g.data.cumulativeScore=String(BigInt(g.data.cumulativeScore)+3000n);});notice('테스트 점수 3,000점을 충전했어요.');}catch(e){notice(e.message);}finally{busy=false;}};
document.addEventListener('visibilitychange',()=>{if(document.hidden)host?.interrupt();});window.addEventListener('pagehide',()=>host?.interrupt());window.addEventListener('pageshow',e=>{if(e.persisted)location.reload();});
(async()=>{try{store=new ProgressStore(new URLSearchParams(location.search).has('test')?'chagok-dice-lab-qa-v1':'chagok-dice-lab-v1',TILE_CASES);await store.open();if(navigator.locks){await navigator.locks.request(new URLSearchParams(location.search).has('test')?'chagok-dice-lab-qa-owner':'chagok-dice-lab-owner',{ifAvailable:true},async lock=>{if(!lock){notice('다른 주사위 테스트 탭을 닫고 새로고침해 주세요.');return;}await connect();await new Promise(()=>{});});}else{if(!await store.lease())throw Error('다른 주사위 테스트 탭을 닫고 새로고침해 주세요.');await connect();setInterval(async()=>{try{if(await store.lease('renew'))return;}catch{}host?.dispose();owner=false;notice('연결이 끊겼어요. 새로고침해 주세요.');},4000);}}catch(e){notice(e.message);}})();
