(function(root){
  'use strict';
  const CONFIG={rulesVersion:'dice-v2',boardSize:5,rollDurationMs:180,countdownMs:3000,timeThresholdsMs:[30000,45000,60000],multipliers:[5,2,1],betStep:100};
  const BASE={U:1,D:6,N:2,S:5,E:3,W:4},DIR={N:[-1,0],S:[1,0],E:[0,1],W:[0,-1]},OPPOSITE={N:'S',S:'N',E:'W',W:'E'};
  function rotate(d,k){const {U,D,N,S,E,W}=d;return {...d,...({N:{U:S,D:N,N:U,S:D,E,W},S:{U:N,D:S,N:D,S:U,E,W},E:{U:W,D:E,N,S,E:U,W:D},W:{U:E,D:W,N,S,E:D,W:U}}[k])};}
  function move(dice,id,k){if(!DIR[k])return null;const d=dice.find(x=>x.diceId===id);if(!d)return null;const row=d.row+DIR[k][0],col=d.col+DIR[k][1];if(row<0||row>4||col<0||col>4||dice.some(x=>x.row===row&&x.col===col))return null;return dice.map(x=>x===d?{...rotate(d,k),row,col}:x);}
  const matched=(dice,goals)=>goals.filter(g=>dice.some(d=>d.row===g.row&&d.col===g.col&&d.U===g.targetValue)).length;
  const orientations=[],queue=[BASE];while(queue.length){const d=queue.shift();if(orientations.some(x=>JSON.stringify(x)===JSON.stringify(d)))continue;orientations.push(d);for(const k of Object.keys(DIR))queue.push(rotate(d,k));}
  function validate(c){try{let d=structuredClone(c.initialDice);if(d.length!==3||c.goals.length!==3||new Set(d.map(x=>x.diceId)).size!==3||d.some(x=>!orientations.some(o=>Object.keys(BASE).every(k=>o[k]===x[k]))||x.row<0||x.row>4||x.col<0||x.col>4||c.goals.some(g=>g.row===x.row&&g.col===x.col))||new Set(d.map(x=>`${x.row},${x.col}`)).size!==3)return false;for(const m of c.verifiedSolution){d=move(d,m.id,m.dir);if(!d)return false;}return matched(d,c.goals)===3;}catch{return false;}}
  function generate(seed){let s=seed>>>0;const random=()=>{s=(Math.imul(s,1664525)+1013904223)>>>0;return s/4294967296;};for(let attempt=0;attempt<200;attempt++){const goals=[1,2,3].map(col=>({row:2,col,targetValue:1+Math.floor(random()*6)}));let dice=goals.map((g,i)=>{const pool=orientations.filter(o=>o.U===g.targetValue);return {...pool[Math.floor(random()*pool.length)],row:g.row,col:g.col,diceId:'ABC'[i]};});const path=[];for(let n=0;n<12+seed%13;n++){const options=[];for(const d of dice)for(const dir of Object.keys(DIR)){if(path.at(-1)?.id===d.diceId&&OPPOSITE[path.at(-1).dir]===dir)continue;const next=move(dice,d.diceId,dir);if(next)options.push({id:d.diceId,dir,next});}const pick=options[Math.floor(random()*options.length)];dice=pick.next;path.push({id:pick.id,dir:pick.dir});}const c={caseId:`dice-${seed}`,goals,initialDice:dice,verifiedSolution:path.reverse().map(m=>({id:m.id,dir:OPPOSITE[m.dir]})),solutionLength:path.length,difficultyBand:'prototype',rulesVersion:CONFIG.rulesVersion};if(new Set(path.map(m=>m.id)).size===3&&validate(c))return c;}throw Error('검증된 주사위 문제를 만들 수 없습니다.');}
  const CASES=Array.from({length:40},(_,i)=>generate(i+1));
  function judge(op,input){if(!['complete','timeout','interrupted','forfeit'].includes(input.reason))throw Error('잘못된 종료 사유');let dice=structuredClone(op.payload.initialDice),last=-180;const moves=input.moves||[];for(const m of moves){if(!Number.isFinite(m.at)||m.at<0||m.at<last+op.config.rollDurationMs)throw Error('잘못된 이동 시각');dice=move(dice,m.id,m.dir);if(!dice)throw Error('잘못된 이동');last=m.at;}const count=matched(dice,op.payload.goals),elapsed=input.elapsedMs;let multiplier=0;if(input.reason==='complete'){if(count!==3||!moves.length||elapsed!==last+op.config.rollDurationMs)throw Error('완료 기록이 올바르지 않습니다.');const i=op.config.timeThresholdsMs.findIndex(t=>elapsed<=t);if(i>=0)multiplier=op.config.multipliers[i];}return {elapsedMs:input.reason==='complete'?elapsed:null,matchedCount:count,moveCount:moves.length,multiplier,endReason:input.reason};}
  class Session{
    constructor(c,config=CONFIG){this.dice=structuredClone(c.initialDice);this.goals=c.goals;this.config=config;this.moves=[];this.pending=null;this.result=null;}
    advance(t){if(this.result)return this.result;const limit=this.config.timeThresholdsMs[2];if(this.pending&&this.pending.end<=Math.min(t,limit)){this.dice=this.pending.dice;this.moves.push(this.pending.move);const end=this.pending.end;this.pending=null;if(matched(this.dice,this.goals)===3)this.result={reason:'complete',elapsedMs:end,moves:this.moves};}if(!this.result&&t>=limit){this.pending=null;this.result={reason:'timeout',elapsedMs:null,moves:this.moves};}return this.result;}
    input(id,dir,t){if(this.advance(t)||this.pending)return false;const next=move(this.dice,id,dir);if(!next)return false;this.pending={dice:next,move:{id,dir,at:t},end:t+this.config.rollDurationMs};return true;}
  }
  const api={CONFIG,BASE,DIR,OPPOSITE,orientations,rotate,move,matched,validate,generate,CASES,judge,Session};if(typeof module!=='undefined')module.exports=api;else root.DiceEngine=api;
})(globalThis);
