const assert=require('node:assert/strict'),E=require('./engine.js'),registry=require('../number-tiles/minigames/catalog.js'),{Game,fresh}=require('../number-tiles/state.js');require('../number-tiles/cases.js');let count=0;const test=(n,f)=>{f();console.log('PASS',n);count++;};
test('24 physical orientations, inverse and four-roll identity',()=>{assert.equal(E.orientations.length,24);for(const [dir,u] of Object.entries({N:5,S:2,E:4,W:3})){assert.equal(E.rotate(E.BASE,dir).U,u);for(const o of E.orientations){assert.deepEqual(E.rotate(E.rotate(o,dir),E.OPPOSITE[dir]),o);let x=o;for(let i=0;i<4;i++)x=E.rotate(x,dir);assert.deepEqual(x,o);assert.equal(o.U+o.D,7);}}});
test('wall and occupied cells cannot alter dice',()=>{const d=[{...E.BASE,diceId:'A',row:0,col:0},{...E.BASE,diceId:'B',row:0,col:1}];const before=JSON.stringify(d);assert.equal(E.move(d,'A','N'),null);assert.equal(E.move(d,'A','E'),null);assert.equal(JSON.stringify(d),before);});
test('40 cases replay legally to simultaneous success',()=>{for(const c of E.CASES){assert(E.validate(c));const s=new E.Session(c);let t=0;for(const m of c.verifiedSolution){if(s.result)break;assert(s.input(m.id,m.dir,t));assert(!s.input(m.id,m.dir,t+1));s.advance(t+180);t+=180;}assert.equal(s.result.reason,'complete');assert.equal(E.judge({payload:c,config:E.CONFIG},s.result).multiplier,5);}});
function ending(t){const c=E.CASES[0],s=new E.Session(c);for(let i=0;i<c.verifiedSolution.length-1;i++){const m=c.verifiedSolution[i];assert(s.input(m.id,m.dir,i*180));s.advance((i+1)*180);}const m=c.verifiedSolution.at(-1);assert(s.input(m.id,m.dir,t-180));return {s,c};}
test('exact 30/45/60 second boundaries and delayed frames',()=>{for(const [t,m] of [[30000,5],[30000.001,2],[30001,2],[45000,2],[45001,1],[60000,1],[60080,0]]){const {s,c}=ending(t);s.advance(65000);const result=E.judge({payload:c,config:E.CONFIG},s.result);assert.equal(result.multiplier,m,`at ${t}`);}});
test('matched goal can become unmatched; duplicate goal digits',()=>{const c=E.CASES.find(c=>new Set(c.goals.map(g=>g.targetValue)).size<3);assert(c);let d=c.initialDice;for(const m of c.verifiedSolution)d=E.move(d,m.id,m.dir);assert.equal(E.matched(d,c.goals),3);const n=E.move(d,'A','N');assert.equal(E.matched(n,c.goals),2);});
function model(){const d=fresh(),p=registry.get('dice_roll');d.cumulativeScore='1076';d.status='minigame';d.pendingMiniGame={...p.create(),type:p.type,miniGameId:'test',sourceRoundId:'round',status:'OFFERED'};return new Game(globalThis.TILE_CASES,d,{recover:false});}
test('shared wallet exact payout, duplicate settlement and reload',()=>{const g=model(),op=g.data.pendingMiniGame;g.mini('start',{stake:'500',expectedBalance:'1076'},'start');g.mini('start',{stake:'500',expectedBalance:'1076'},'start');assert.equal(g.data.cumulativeScore,'576');g.mini('running');const s=new E.Session(op.payload);for(let i=0;i<op.payload.verifiedSolution.length&&!s.result;i++){const m=op.payload.verifiedSolution[i];s.input(m.id,m.dir,i*180);s.advance((i+1)*180);}g.mini('settle',s.result,'result');g.mini('settle',s.result,'result-again');assert.equal(g.data.cumulativeScore,'3076');assert.equal(g.data.pendingMiniGame.result.netChange,'2000');const restored=new Game(globalThis.TILE_CASES,g.data);assert.equal(restored.data.cumulativeScore,'3076');assert.equal(restored.data.miniGameHistory.length,1);});
test('invalid case blocks debit; interruption recovery loses stake once',()=>{const g=model();g.data.pendingMiniGame.payload.initialDice[0].U=99;assert.throws(()=>g.mini('start',{stake:'500',expectedBalance:'1076'}));assert.equal(g.data.cumulativeScore,'1076');for(const running of [false,true]){const x=model();x.mini('start',{stake:'1000',expectedBalance:'1076'});if(running)x.mini('running');const r=new Game(globalThis.TILE_CASES,x.data);assert.equal(r.data.cumulativeScore,'76');assert.equal(r.data.pendingMiniGame.result.multiplier,0);assert.equal(new Game(globalThis.TILE_CASES,r.data).data.cumulativeScore,'76');}});
test('both minigames have equal draw weight',()=>{assert.equal(registry.get('dice_roll').weight,registry.get('timer_stop').weight);assert.equal(registry.get('number_memory').weight,1);assert.equal(registry.draw(()=>.3).type,'dice_roll');assert.equal(registry.draw(()=>.5).type,'timer_stop');});
console.log(`${count} dice suites passed`);
