(function(root){
 const E=root.DiceEngine;
 root.DiceView={mount(ctx){
  let op=ctx.opportunity,session=null,start=0,frame=0,timer=0,disposed=false,finished=false,selected='A',gesture=null,audio=null,muted=false;
  const el=ctx.container;
  el.innerHTML=`<div class="dice-heading"><div><h2>주사위 굴리기</h2></div><button id="dice-sound" aria-label="소리 켜기">소리 꺼짐</button></div><div class="dice-stats"><div><small>남은 시간</small><b id="dice-time">${op.config.timeThresholdsMs[2]/1000}초</b></div><div><small>현재 배당</small><b id="dice-rate">×5</b></div></div><div class="dice-timebar"><i id="dice-timebar"></i></div><div class="dice-targets" id="dice-targets"></div><div class="dice-board" id="dice-board"><div class="dice-curtain"><small>GET READY</small><strong id="dice-count">3</strong><span>보드가 열리면 시작해요</span></div></div><div id="dice-selection" class="dice-selection"></div><div class="dice-bottom"><div><span class="eyebrow">선택한 주사위의 면</span><div id="dice-faces" class="dice-net"></div></div><div class="dice-pad"><button data-dir="N" aria-label="위로 굴리기">↑</button><button data-dir="W" aria-label="왼쪽으로 굴리기">←</button><button data-dir="S" aria-label="아래로 굴리기">↓</button><button data-dir="E" aria-label="오른쪽으로 굴리기">→</button></div></div><p id="dice-hint" class="dice-hint" role="status">선택한 주사위를 굴리세요</p><button id="dice-giveup" class="mini-secondary">포기하기 · 환급 없음</button>`;
  const q=s=>el.querySelector(s),board=q('#dice-board');muted=true;
  q('#dice-sound').onclick=()=>{muted=!muted;q('#dice-sound').textContent=muted?'소리 꺼짐':'소리 켜짐';q('#dice-sound').setAttribute('aria-label',muted?'소리 켜기':'소리 끄기');if(!muted){audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();}};
  function sound(){if(muted||!audio)return;const osc=audio.createOscillator(),gain=audio.createGain();osc.connect(gain);gain.connect(audio.destination);osc.frequency.setValueAtTime(240,audio.currentTime);osc.frequency.exponentialRampToValueAtTime(100,audio.currentTime+.055);gain.gain.setValueAtTime(.06,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.065);osc.start();osc.stop(audio.currentTime+.07);}
  function cube(d){return `<div class="dice-cube"><div class="cube-face face-u">${d.U}</div><div class="cube-face face-d">${d.D}</div><div class="cube-face face-n">${d.N}</div><div class="cube-face face-s">${d.S}</div><div class="cube-face face-e">${d.E}</div><div class="cube-face face-w">${d.W}</div></div>`;}
  function render(){if(!session)return;board.innerHTML=Array.from({length:25},(_,i)=>{const g=session.goals.find(g=>g.row===Math.floor(i/5)&&g.col===i%5),ok=g&&E.matched(session.dice,[g]);return `<div class="dice-cell ${g?'goal':''} ${ok?'matched':''}">${g?`<span>${g.targetValue}${ok?' ✓':''}</span>`:''}</div>`;}).join('')+session.dice.map(d=>`<button class="dice-piece die-${d.diceId} ${d.diceId===selected?'selected':''}" data-id="${d.diceId}" style="--row:${d.row};--col:${d.col}" aria-label="주사위 ${d.diceId}, 윗면 ${d.U}">${cube(d)}<span class="dice-id">${d.diceId}</span></button>`).join('');
   q('#dice-targets').innerHTML=`<small>중앙 목표</small>${session.goals.map(g=>`<span class="${E.matched(session.dice,[g])?'done':''}">${g.targetValue}<i>${E.matched(session.dice,[g])?'✓':'·'}</i></span>`).join('')}<small>${E.matched(session.dice,session.goals)} / 3 일치</small>`;
   q('#dice-selection').innerHTML=session.dice.map(d=>`<button data-select="${d.diceId}" class="die-${d.diceId} ${selected===d.diceId?'active':''}">${d.diceId} <b>${d.U}</b></button>`).join('');renderFaces();
  }
  function renderFaces(){const d=session.dice.find(d=>d.diceId===selected);q('#dice-faces').innerHTML=['N','W','U','E','S'].map(k=>`<span class="net-${k}"><small>${{N:'북',W:'서',U:'위',E:'동',S:'남'}[k]}</small>${d[k]}</span>`).join('');}
  function finish(payload){if(disposed||finished)return;finished=true;cancelAnimationFrame(frame);clearTimeout(timer);ctx.settle(payload);}
  function tick(){if(disposed||finished||!session)return;const t=performance.now()-start,pending=session.pending,result=session.advance(t);if(pending&&!session.pending){render();sound();}if(result){finish(result);return;}const limits=op.config.timeThresholdsMs,limit=limits[2],band=limits.findIndex(v=>t<=v);q('#dice-time').textContent=`${Math.max(0,(limit-t)/1000).toFixed(1)}초`;q('#dice-rate').textContent=`×${op.config.multipliers[band]}`;q('#dice-timebar').style.width=`${100-t/limit*100}%`;frame=requestAnimationFrame(tick);}
  function select(id){if(!session||session.pending||finished)return;selected=id;render();}
  function roll(dir){if(!session||disposed||finished||session.pending)return;const t=performance.now()-start;if(!session.input(selected,dir,t)){if(session.result)finish(session.result);else{q('#dice-hint').textContent='그쪽은 막혀 있어요. 다른 방향으로 굴려보세요.';}return;}q('#dice-hint').textContent='선택한 주사위를 굴리세요';const piece=board.querySelector(`[data-id="${selected}"]`),cube=piece.querySelector('.dice-cube'),delta=E.DIR[dir],cell=board.clientWidth/5;
   // Pivot at the leading floor edge: x=right, y=south, z=up.
   cube.style.transformOrigin={N:'50% 0 calc(var(--cube) / -2)',S:'50% 100% calc(var(--cube) / -2)',E:'100% 50% calc(var(--cube) / -2)',W:'0 50% calc(var(--cube) / -2)'}[dir];
   const half=(cell-parseFloat(getComputedStyle(board).getPropertyValue('--cube')))/2;
   piece.animate([{transform:'translate(0,0)'},{transform:`translate(${delta[1]*half}px,${delta[0]*half}px)`},{transform:`translate(${delta[1]*half*2}px,${delta[0]*half*2}px)`}],{duration:180,fill:'forwards'});
   cube.animate([{transform:'rotateX(0deg) rotateY(0deg)'},{transform:{N:'rotateX(90deg)',S:'rotateX(-90deg)',E:'rotateY(90deg)',W:'rotateY(-90deg)'}[dir]}],{duration:180,fill:'forwards',easing:'ease-in-out'});
  }
  el.onclick=e=>{const d=e.target.closest('[data-dir]'),s=e.target.closest('[data-select]');if(d)roll(d.dataset.dir);if(s)select(s.dataset.select);};
  board.onpointerdown=e=>{if(gesture||!session||session.pending||finished||e.button!==0)return;const p=e.target.closest('[data-id]');if(!p)return;select(p.dataset.id);gesture={id:e.pointerId,x:e.clientX,y:e.clientY};board.setPointerCapture(e.pointerId);};
  board.onpointerup=e=>{if(!gesture||e.pointerId!==gesture.id)return;const dx=e.clientX-gesture.x,dy=e.clientY-gesture.y;gesture=null;if(Math.max(Math.abs(dx),Math.abs(dy))<20||Math.abs(dx)===Math.abs(dy))return;roll(Math.abs(dx)>Math.abs(dy)?dx>0?'E':'W':dy>0?'S':'N');};board.onpointercancel=()=>gesture=null;
  function key(e){if(e.repeat)return;const dir={ArrowUp:'N',ArrowDown:'S',ArrowRight:'E',ArrowLeft:'W'}[e.key];if(dir){e.preventDefault();roll(dir);}if(['1','2','3'].includes(e.key))select('ABC'[Number(e.key)-1]);}document.addEventListener('keydown',key);
  q('#dice-giveup').onclick=()=>{if(session)finish({reason:'forfeit',elapsedMs:null,moves:session.moves});else finish({reason:'interrupted',elapsedMs:null});};
  function run(){if(session||disposed)return;session=new E.Session(op.payload,op.config);render();start=performance.now();tick();}
  const countEnd=performance.now()+op.config.countdownMs;function countdown(){if(disposed||finished)return;const remain=countEnd-performance.now();if(remain<=0){ctx.command('running').catch(()=>finish({reason:'interrupted',elapsedMs:null}));return;}q('#dice-count').textContent=Math.ceil(remain/1000);timer=setTimeout(countdown,Math.min(100,remain));}
  function update(next){op=next;if(op.status==='RUNNING')run();}if(op.status==='COUNTDOWN')countdown();else run();
  return {update,interruption:()=>({reason:'interrupted',elapsedMs:null,moves:session?.moves||[]}),dispose(){disposed=true;cancelAnimationFrame(frame);clearTimeout(timer);document.removeEventListener('keydown',key);audio?.close();}};
 }};
})(globalThis);
