(async()=>{
  const E=VaultEngine,fixture=document.getElementById('fixture'),contents=Array.from({length:12},(_,i)=>i<9?'TREASURE':'BOMB'),assert=(v,m)=>{if(!v)throw Error(m);},sleep=ms=>new Promise(r=>setTimeout(r,ms));let passed=0,failed=0,host,game,failNext=false,sent=[];
  async function test(name,fn){try{await fn();const li=document.createElement('li');li.textContent=`PASS ${name}`;document.getElementById('results').append(li);passed++;}catch(e){const li=document.createElement('li');li.textContent=`FAIL ${name}: ${e.message}`;document.getElementById('results').append(li);failed++;}finally{host?.dispose();host=null;}}
  async function until(fn){const end=performance.now()+3000;while(!fn()){if(performance.now()>end)throw Error('상태 전환 시간 초과');await sleep(5);}}
  const store=new ProgressStore(`vault-test-${MiniGames.uid()}`,TILE_CASES);await store.open();
  const q=s=>fixture.querySelector(s),o=()=>game.data.pendingMiniGame;
  async function offer(){const saved=await store.update(g=>{g.data=TileState.fresh();g.data.status='minigame';g.data.cumulativeScore='1076';g.data.pendingMiniGame={...MiniGames.registry.get('risky_vault').create(),type:'risky_vault',miniGameId:MiniGames.uid(),status:'OFFERED',payload:{contents}};g.data.pendingMiniGame.config.revealMs=50;});game=saved.model;}
  async function command(type,payload,eventId){sent.push({type,eventId});const fail=failNext;failNext=false;const saved=await store.update(g=>{g.mini(type,payload,eventId);if(fail)g.data.invalid=()=>{};});game=saved.model;host.show();}
  function mount(){host=new MiniGameHost({container:fixture,getData:()=>game.data,command,next:()=>{},notice:()=>{}});host.show();}
  async function begin(){failNext=false;sent=[];await offer();game=(await store.update(g=>g.mini('start',{stake:'500',expectedBalance:'1076'}))).model;mount();}
  function direct(g,type,input={}){g.mini(type,{expectedVersion:g.data.pendingMiniGame.progress.version,...input});}
  async function open(i){q(`[data-cell="${i}"]`).click();await until(()=>o().status==='DECIDING'||o().status==='SETTLED');}
  async function more(){q('#vault-continue').click();await until(()=>o().status==='SELECTING');}
  await test('준비 안내는 중단 복원 · 숨은 금고 내용 비노출',async()=>{await offer();mount();assert(fixture.textContent.includes('앱을 나가도 배치와 진행이 그대로 저장'),'잘못된 중단 안내');host.dispose();await begin();const cells=[...fixture.querySelectorAll('[data-cell]')];assert(cells.length===12,'12칸');assert(cells.every(b=>b.getAttribute('aria-label').includes('닫힌 금고')&&b.querySelector('.vault-content').textContent===''),'내용 노출');assert(q('#vault-cashout').disabled,'첫 선택 전 종료');assert(q('#vault-remaining').textContent.includes('폭탄 3개'),'위험 표시');});
  await test('저장 실패 시 비공개 · 같은 이벤트로 재시도',async()=>{await begin();failNext=true;q('[data-cell="0"]').click();await until(()=>q('#vault-retry')&&!q('#vault-retry').hidden);assert(o().status==='SELECTING'&&o().progress.openedCellIds.length===0,'실패한 선택 반영');assert(q('[data-cell="0"] .vault-content').textContent==='','실패 결과 노출');const first=sent[0].eventId;q('#vault-retry').click();await until(()=>o().status==='DECIDING');assert(sent[1].eventId===first,'재시도 ID 변경');assert(q('[data-cell="0"]').textContent.includes('보물'),'공개 누락');});
  await test('결정 화면 잠금 · 계속 후 종료 · 1.5배 정확 지급',async()=>{await begin();await open(0);q('[data-cell="1"]').click();assert(o().progress.openedCellIds.length===1,'계속 없이 개봉');assert(game.data.cumulativeScore==='576','미확정 금액 지급');await more();await open(1);assert(q('#vault-cashout').textContent.includes('750'),'현재 지급액');assert(q('#vault-risk').textContent.includes('30.0%'),'다음 폭탄 확률');await more();q('#vault-cashout').click();await until(()=>o().status==='SETTLED'&&q('#mini-next'));assert(game.data.cumulativeScore==='1326','분수 정산');assert(fixture.querySelectorAll('.vault-review-cell').length===12,'전체 배치 복기');});
  await test('다중 터치·연타 잠금과 모바일 금고 크기',async()=>{await begin();const root=fixture.querySelector('#mini-runtime');root.setPointerCapture=()=>{};const target=q('[data-cell="0"]'),rect=target.getBoundingClientRect();assert(rect.width>=64&&rect.height>=64,'터치 크기');assert(fixture.scrollWidth<=282,'가로 넘침');const pointer=(cell,id)=>q(`[data-cell="${cell}"]`).dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,pointerId:id,button:0}));pointer(0,1);pointer(1,2);q('[data-cell="2"]').dispatchEvent(new MouseEvent('click',{bubbles:true,detail:1}));await until(()=>o().status==='DECIDING');assert(o().progress.openedCellIds.length===1,'복수 개봉');});
  await test('개봉 결과 저장 후 중단 · 복원 뒤 배치와 지급액 유지',async()=>{await begin();host.dispose();game=(await store.update(g=>direct(g,'vault_open',{cellId:0}))).model;assert(o().status==='REVEALING','공개 상태');game=(await store.initialize()).model;mount();assert(o().status==='DECIDING'&&o().progress.treasureCount===1,'공개 복원');host.interrupt();assert(o().status==='DECIDING'&&game.data.cumulativeScore==='576','중단 몰수');await more();const before=JSON.stringify(o());game=(await store.initialize()).model;assert(JSON.stringify(o())===before,'선택 복원 변동');});
  await test('폭탄과 5개 성공은 공개 전에 원자적 정산 · 복원 중복 없음',async()=>{for(const bomb of [true,false]){await begin();if(bomb)q('[data-cell="9"]').click();else{for(let i=0;i<4;i++){await open(i);await more();}q('[data-cell="4"]').click();}await until(()=>o().status==='SETTLED');assert(game.data.cumulativeScore===(bomb?'576':'3076'),'즉시 정산');await until(()=>q('#mini-next'));assert(o().result.endReason===(bomb?'bomb':'complete'),'종료 사유');game=(await store.initialize()).model;assert(game.data.cumulativeScore===(bomb?'576':'3076')&&game.data.miniGameHistory.length===1,'중복 지급');host.dispose();}});
  await test('동시 지급/개봉 요청은 먼저 저장된 한 동작만 반영',async()=>{for(const order of [['vault_open','vault_cashout'],['vault_cashout','vault_open']]){await begin();await open(0);await more();const version=o().progress.version,results=await Promise.allSettled(order.map(type=>store.update(g=>g.mini(type,{cellId:1,expectedVersion:version}))));assert(results.filter(r=>r.status==='fulfilled').length===1,'동시 동작 반영');game=(await store.update(()=>{})).model;assert(game.data.cumulativeScore===(order[0]==='vault_open'?'576':'1076'),'동시 지급 오류');host.dispose();}});
  await test('동시 베팅과 시작 저장 실패도 차감 한 번',async()=>{await offer();try{await store.update(g=>{g.mini('start',{stake:'500',expectedBalance:'1076'});g.data.invalid=()=>{};});}catch{}game=(await store.update(()=>{})).model;assert(game.data.cumulativeScore==='1076'&&o().status==='OFFERED','시작 롤백');const results=await Promise.allSettled([store.update(g=>g.mini('start',{stake:'500',expectedBalance:'1076'},'bet-a')),store.update(g=>g.mini('start',{stake:'500',expectedBalance:'1076'},'bet-b'))]);assert(results.filter(r=>r.status==='fulfilled').length===1,'중복 베팅');game=(await store.update(()=>{})).model;assert(game.data.cumulativeScore==='576','중복 차감');});
  store.db.close();indexedDB.deleteDatabase(store.name);fixture.innerHTML='';document.getElementById('summary').textContent=`${passed} passed · ${failed} failed`;
})();
