const assert=require('node:assert/strict'),E=require('./engine.js'),registry=require('../number-tiles/minigames/catalog.js'),{Game,fresh}=require('../number-tiles/state.js');require('../number-tiles/cases.js');let count=0,sequence=0;
const contents=Array.from({length:12},(_,i)=>i<9?'TREASURE':'BOMB');
const test=(name,fn)=>{fn();console.log('PASS',name);count++;};
function model(balance='1076'){const d=fresh(),plugin=registry.get('risky_vault');d.status='minigame';d.cumulativeScore=balance;d.pendingMiniGame={...plugin.create(),type:plugin.type,miniGameId:'vault-test',sourceRoundId:'round',status:'OFFERED',payload:{contents:[...contents]}};return new Game(globalThis.TILE_CASES,d,{recover:false});}
function cmd(g,type,input={},id=`event-${++sequence}`){return g.mini(type,{expectedVersion:g.data.pendingMiniGame.progress?.version,...input},id);}
function start(g,stake='500'){g.mini('start',{stake,expectedBalance:g.data.cumulativeScore});}
function treasure(g,n){for(let i=0;i<n;i++){if(i)cmd(g,'vault_continue');cmd(g,'vault_open',{cellId:i});if(g.data.pendingMiniGame.status!=='SETTLED')cmd(g,'vault_revealed');}}
test('12 cells, nine treasures and three bombs; invalid data blocked',()=>{for(let i=0;i<500;i++){const a=E.generate();assert(E.validate(a));assert.equal(a.filter(x=>x==='TREASURE').length,9);}assert(!E.validate(contents.slice(1)));assert(!E.validate(Array(12).fill('TREASURE')));const g=model();g.data.pendingMiniGame.payload.contents[0]='BOMB';assert.throws(()=>start(g));assert.equal(g.data.cumulativeScore,'1076');});
test('start debits once without countdown; K0 cannot cash out',()=>{const g=model();g.mini('start',{stake:'500',expectedBalance:'1076'},'debit');g.mini('start',{stake:'500',expectedBalance:'1076'},'debit');assert.equal(g.data.cumulativeScore,'576');assert.equal(g.data.pendingMiniGame.status,'SELECTING');assert.throws(()=>cmd(g,'vault_cashout'));});
test('treasure opens before deciding but never credits provisional payout',()=>{const g=model();start(g);cmd(g,'vault_open',{cellId:0});const o=g.data.pendingMiniGame;assert.equal(o.status,'REVEALING');assert.equal(o.progress.treasureCount,1);assert.equal(o.progress.pendingReveal.content,'TREASURE');assert.equal(g.data.cumulativeScore,'576');assert.throws(()=>cmd(g,'vault_open',{cellId:1}));assert.throws(()=>cmd(g,'vault_cashout'));cmd(g,'vault_revealed');assert.equal(o.status,'DECIDING');assert.throws(()=>cmd(g,'vault_open',{cellId:1}));const before=structuredClone(o.progress);cmd(g,'vault_open',{cellId:0});assert.deepEqual(o.progress,before);});
test('all five payout tiers and 1.5x example preserve every point',()=>{for(const [k,payout]of [[1,500],[2,750],[3,1000],[4,1500],[5,2500]]){const g=model();start(g);treasure(g,k);if(k<5)cmd(g,'vault_cashout');const r=g.data.pendingMiniGame.result;assert.equal(r.payout,String(payout));assert.equal(g.data.cumulativeScore,String(576+payout));assert.equal(r.netChange,String(payout-500));assert.equal(r.endReason,k===5?'complete':'cashout');if(k===2)assert.equal(BigInt(g.data.cumulativeScore)/100n*100n,1300n);}});
test('100-point stake pays 150, huge integer stake stays exact',()=>{for(const [balance,stake]of [['1076','100'],['900719925474099312345600','900719925474099312345600']]){const g=model(balance);start(g,stake);treasure(g,2);cmd(g,'vault_cashout');assert.equal(g.data.pendingMiniGame.result.payout,String(BigInt(stake)*3n/2n));assert.equal(g.data.cumulativeScore,String(BigInt(balance)+BigInt(stake)/2n));}});
test('bomb after four treasures discards provisional amount with no second debit',()=>{const g=model();start(g);treasure(g,4);cmd(g,'vault_continue');cmd(g,'vault_open',{cellId:9});assert.equal(g.data.pendingMiniGame.status,'SETTLED');assert.equal(g.data.pendingMiniGame.result.treasureCount,4);assert.equal(g.data.pendingMiniGame.result.payout,'0');assert.equal(g.data.cumulativeScore,'576');});
test('five treasures automatically settle; retries cannot open or pay twice',()=>{const g=model();start(g);treasure(g,4);cmd(g,'vault_continue');const version=g.data.pendingMiniGame.progress.version;cmd(g,'vault_open',{cellId:4,expectedVersion:version},'final-open');cmd(g,'vault_open',{cellId:4,expectedVersion:version},'final-open');assert.throws(()=>cmd(g,'vault_open',{cellId:5}));assert.throws(()=>cmd(g,'vault_cashout'));assert.equal(g.data.cumulativeScore,'3076');assert.equal(g.data.miniGameHistory.length,1);});
test('continue unlocks exactly one choice and keeps cashout available',()=>{const g=model();start(g);treasure(g,2);cmd(g,'vault_continue');assert.equal(g.data.pendingMiniGame.status,'SELECTING');assert.equal(g.data.pendingMiniGame.progress.openedCellIds.length,2);cmd(g,'vault_cashout');assert.equal(g.data.cumulativeScore,'1326');});
test('every risk display matches remaining treasure and three bombs',()=>{for(let k=0;k<5;k++){const r=E.risk(k);assert.equal(r.remaining,12-k);assert.equal(r.treasures,9-k);assert.equal(r.bombs,3);assert.equal(r.bombProbability,3/(12-k));}assert.equal(E.risk(4).bombProbability,.375);});
test('offered, selecting, revealing, deciding and settled all restore',()=>{const offered=model();assert.deepEqual(new Game(globalThis.TILE_CASES,offered.data).data.pendingMiniGame.payload.contents,contents);for(const state of ['SELECTING','REVEALING','DECIDING','SETTLED']){const g=model();start(g);if(state!=='SELECTING')cmd(g,'vault_open',{cellId:0});if(['DECIDING','SETTLED'].includes(state))cmd(g,'vault_revealed');if(state==='SETTLED')cmd(g,'vault_cashout');const restored=new Game(globalThis.TILE_CASES,g.data),o=restored.data.pendingMiniGame;assert.equal(o.status,state==='REVEALING'?'DECIDING':state);assert.equal(restored.data.cumulativeScore,g.data.cumulativeScore);assert.deepEqual(o.payload.contents,contents);assert.deepEqual(o.progress.openedCellIds,g.data.pendingMiniGame.progress.openedCellIds);if(state==='REVEALING')assert.equal(o.progress.pendingReveal,null);assert.equal(new Game(globalThis.TILE_CASES,restored.data).data.cumulativeScore,restored.data.cumulativeScore);}});
test('version guards simultaneous cashout and open in either order',()=>{for(const first of ['vault_open','vault_cashout']){const g=model();start(g);treasure(g,1);cmd(g,'vault_continue');const version=g.data.pendingMiniGame.progress.version;cmd(g,first,{cellId:1,expectedVersion:version});assert.throws(()=>cmd(g,first==='vault_open'?'vault_cashout':'vault_open',{cellId:1,expectedVersion:version}));assert.equal(g.data.cumulativeScore,first==='vault_open'?'576':'1076');}});
test('invalid bets, out-of-board input and direct settlement blocked',()=>{const g=model();for(const stake of ['0','99','150','1100','100.5'])assert.throws(()=>start(g,stake));g.data.cumulativeScore='99';assert.throws(()=>start(g,'100'));g.data.cumulativeScore='1076';start(g);for(const cellId of [-1,12,.5])assert.throws(()=>cmd(g,'vault_open',{cellId}));assert.throws(()=>g.mini('settle',{reason:'interrupted'}));assert.equal(g.data.cumulativeScore,'576');});
test('configuration snapshot retained across restore and new defaults',()=>{const g=model();start(g);treasure(g,2);const old=structuredClone(E.CONFIG.payoutTiers[1]);try{E.CONFIG.payoutTiers[1]={numerator:9,denominator:1};const restored=new Game(globalThis.TILE_CASES,g.data);cmd(restored,'vault_cashout');assert.equal(restored.data.pendingMiniGame.result.payout,'750');}finally{E.CONFIG.payoutTiers[1]=old;}});
test('five equal draws, existing time settings, and final stage exits',()=>{assert.deepEqual(registry.list().map(x=>x.weight),[1,1,1,1,1]);assert.equal(registry.draw(()=>.9).type,'risky_vault');assert.equal(require('../number-memory/engine.js').CONFIG.revealMs,4000);assert.deepEqual(require('../dice-roll/engine.js').CONFIG.timeThresholdsMs,[30000,45000,60000]);for(const skip of [true,false]){const g=model();g.data.currentTarget=21;if(skip)g.mini('skip');else{start(g);treasure(g,1);cmd(g,'vault_cashout');}g.next();assert.equal(g.data.status,'finished');}});
console.log(`${count} vault suites passed`);
